In [1]:

from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

search_roots = [
    PROJECT_ROOT / "data",
    PROJECT_ROOT / "Notebooks 2",
]

keywords = (
    "feature", "train", "test", "manifest",
    "model", "scaler", "traditional", "ml",
    "experiment_b"
)

extensions = {
    ".csv", ".npz", ".npy", ".joblib",
    ".pkl", ".pickle", ".json", ".parquet"
}

matches = set()

for root in search_roots:
    if not root.exists():
        continue

    for path in root.rglob("*"):
        if not path.is_file():
            continue

        if path.suffix.lower() not in extensions:
            continue

        if any(word in path.name.lower() for word in keywords):
            matches.add(path)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("\nPotential existing ML artifacts:\n")

for path in sorted(matches):
    try:
        relative_path = path.relative_to(PROJECT_ROOT)
    except ValueError:
        relative_path = path

    print(relative_path)

PROJECT_ROOT: /Users/vs/Sem 5/Respiratory-Disease-Classification

Potential existing ML artifacts:

data/processed/analysis/.ipynb_checkpoints/sound_feature_means-checkpoint.csv
data/processed/analysis/crackle_feature_correlations.csv
data/processed/analysis/crackle_feature_means.csv
data/processed/analysis/disease_feature_means.csv
data/processed/analysis/feature_coefficient_variation.csv
data/processed/analysis/feature_statistics.csv
data/processed/analysis/feature_variance.csv
data/processed/analysis/sound_feature_means.csv
data/processed/analysis/wheeze_feature_correlations.csv
data/processed/analysis/wheeze_feature_means.csv
data/processed/classical_ml/.ipynb_checkpoints/classical_ml_model_comparison-checkpoint.csv
data/processed/classical_ml/.ipynb_checkpoints/classical_ml_per_disease_results-checkpoint.csv
data/processed/classical_ml/classical_ml_model_comparison.csv
data/processed/classical_ml/classical_ml_per_disease_results.csv
data/processed/classical_ml/classical_ml_predictions.csv
data/processed/classical_ml/classical_ml_selected_features.csv
data/processed/classical_ml/final_classical_ml_comparison.csv
data/processed/classical_ml/random_forest_feature_group_importance.csv
data/processed/classical_ml/random_forest_feature_importance.csv
data/processed/deep_learning/X_test_logmel.npy
data/processed/deep_learning/X_train_logmel.npy
data/processed/deep_learning/cnn_baseline/cnn_patient_disjoint_manifest.csv
data/processed/deep_learning/cnn_baseline/cnn_test_predictions.csv
data/processed/deep_learning/cnn_baseline/cnn_training_class_weights.csv
data/processed/deep_learning/cnn_baseline/cnn_training_config.json
data/processed/deep_learning/cnn_baseline/cnn_training_history.csv
data/processed/deep_learning/cnn_baseline/test_cnn_manifest.csv
data/processed/deep_learning/cnn_baseline/train_cnn_manifest.csv
data/processed/deep_learning/cnn_baseline/validation_cnn_manifest.csv
data/processed/deep_learning/cnn_lstm/cnn_lstm_test_predictions.csv
data/processed/deep_learning/cnn_lstm/cnn_lstm_training_class_weights.csv
data/processed/deep_learning/cnn_lstm/cnn_lstm_training_config.json
data/processed/deep_learning/cnn_lstm/cnn_lstm_training_history.csv
data/processed/deep_learning/cnn_lstm/cnn_model_comparison.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_class_support_audit.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_normalization_stats.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/checkpoints/experiment_b_lightweight_cnn_config.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/checkpoints/experiment_b_lightweight_cnn_history.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/experiment_b_test_summary.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/experiment_b_test_summary.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/fraiwan_external_test_classification_report.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/fraiwan_external_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/fraiwan_external_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/icbhi_test_classification_report.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/icbhi_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/evaluation/icbhi_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/fraiwan_test_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/icbhi_test_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/inner_train_recordings.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/train_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_v1_strict/validation_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/experiment_b_window_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/fraiwan_test_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/icbhi_test_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_feature_cache/train_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_fraiwan_test_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_icbhi_test_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_b_train_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_fraiwan_external_test_classification_report.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_fraiwan_external_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_fraiwan_external_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_icbhi_test_classification_report.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_icbhi_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_icbhi_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_test_summary.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation/c1_test_summary.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/fraiwan_test_classification_report.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/fraiwan_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/fraiwan_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/icbhi_test_classification_report.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/icbhi_test_confusion_matrix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/evaluation_c1_normalized/icbhi_test_recording_predictions.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/test_features_c1_normalized/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/test_features_c1_normalized/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/train_window_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c1_icbhi_only/validation_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_compact_multifeature_training_history.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_fraiwan_test_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_icbhi_test_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_train_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_train_manifest_before_lrti_fix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_validation_manifest.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/c2_validation_manifest_before_lrti_fix.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/feature_extraction_config.json
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/fraiwan_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/icbhi_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/train_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1/validation_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1_normalized/fraiwan_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1_normalized/icbhi_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1_normalized/train_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_logmel_v1_normalized/validation_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/fraiwan_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/icbhi_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/train_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1/validation_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1_normalized/fraiwan_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1_normalized/icbhi_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1_normalized/train_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v1_normalized/validation_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/fraiwan_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/fraiwan_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/icbhi_test_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/icbhi_test_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/train_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/train_metadata.csv
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2/validation_features.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2_normalized/fraiwan_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2_normalized/icbhi_test_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2_normalized/train_features_normalized.npz
data/processed/deep_learning/combined_icbhi_fraiwan_hf_lung_v1/experiment_c2_icbhi_fraiwan_high_capacity/features_multifeature_v2_normalized/validation_features_normalized.npz
data/processed/deep_learning/combined_phenotype/icbhi_phenotype_manifest.csv
data/processed/deep_learning/deep_learning_manifest.csv
data/processed/deep_learning/final_model_comparison_summary.json
data/processed/deep_learning/imbalance_comparison/common_patient_holdout_predictions/experiment_A_weighted_ce_test_predictions.csv
data/processed/deep_learning/imbalance_comparison/common_patient_holdout_predictions/experiment_B_balanced_sampler_test_predictions.csv
data/processed/deep_learning/imbalance_comparison/experiment_B_balanced_sampler_history.csv
data/processed/deep_learning/imbalance_comparison/experiment_B_balanced_sampler_validation_metrics.json
data/processed/deep_learning/imbalance_comparison/experiment_B_balanced_sampler_validation_report.csv
data/processed/deep_learning/lightweight_multifeature_cnn/feature_cache/test_features.npz
data/processed/deep_learning/lightweight_multifeature_cnn/feature_cache/train_features.npz
data/processed/deep_learning/lightweight_multifeature_cnn/feature_cache/validation_features.npz
data/processed/deep_learning/lightweight_multifeature_cnn/feature_config.json
data/processed/deep_learning/lightweight_multifeature_cnn/test_classification_report.csv
data/processed/deep_learning/lightweight_multifeature_cnn/test_confusion_matrix.csv
data/processed/deep_learning/lightweight_multifeature_cnn/test_metrics.json
data/processed/deep_learning/lightweight_multifeature_cnn/test_predictions.csv
data/processed/deep_learning/lightweight_multifeature_cnn/training_config.json
data/processed/deep_learning/lightweight_multifeature_cnn/training_history.csv
data/processed/deep_learning/lightweight_multifeature_cnn/training_summary.json
data/processed/deep_learning/logmel_test_errors.csv
data/processed/deep_learning/logmel_train_errors.csv
data/processed/deep_learning/logmel_train_normalization.csv
data/processed/deep_learning/multidataset_pretraining/hf_fraiwan_phenotype_train_manifest.csv
data/processed/deep_learning/multidataset_pretraining/hf_phenotype_pretrain_train.csv
data/processed/deep_learning/multidataset_pretraining/hf_phenotype_pretrain_validation.csv
data/processed/deep_learning/multidataset_pretraining/hf_phenotype_train_manifest.csv
data/processed/deep_learning/multidataset_pretraining/hf_phenotype_training_history.csv
data/processed/deep_learning/multidataset_pretraining/phenotype_pretraining_manifest.csv
data/processed/deep_learning/multifeature_cnn/cnn_baseline_vs_multifeature_comparison.csv
data/processed/deep_learning/multifeature_cnn/multifeature_cnn_confusion_matrix.csv
data/processed/deep_learning/multifeature_cnn/multifeature_cnn_metrics.csv
data/processed/deep_learning/multifeature_cnn/multifeature_cnn_test_predictions.csv
data/processed/deep_learning/multifeature_cnn/multifeature_cnn_training_config.json
data/processed/deep_learning/multifeature_cnn/multifeature_cnn_training_history.csv
data/processed/deep_learning/multifeature_cnn/multifeature_train_normalization.csv
data/processed/deep_learning/multifeature_cnn/multifeature_training_class_weights.csv
data/processed/deep_learning/multifeature_cnn_12b/test_predictions.csv
data/processed/deep_learning/multifeature_cnn_12b/training_config.json
data/processed/deep_learning/multifeature_cnn_12b/training_history.csv
data/processed/deep_learning/test_manifest.csv
data/processed/deep_learning/train_manifest.csv
data/processed/deep_learning/y_test.npy
data/processed/deep_learning/y_train.npy
data/processed/feature_selection/.ipynb_checkpoints/anova_feature_scores-checkpoint.csv
data/processed/feature_selection/.ipynb_checkpoints/feature_selection_ranking-checkpoint.csv
data/processed/feature_selection/.ipynb_checkpoints/random_forest_feature_importance-checkpoint.csv
data/processed/feature_selection/.ipynb_checkpoints/selected_features-checkpoint.csv
data/processed/feature_selection/anova_feature_scores.csv
data/processed/feature_selection/feature_selection_ranking.csv
data/processed/feature_selection/final_feature_selection_ranking.csv
data/processed/feature_selection/random_forest_feature_importance.csv
data/processed/feature_selection/selected_features.csv
data/processed/features/.ipynb_checkpoints/feature_extraction_errors-checkpoint.csv
data/processed/features/.ipynb_checkpoints/respiratory_cycle_features-checkpoint.csv
data/processed/features/feature_extraction_errors.csv
data/processed/features/respiratory_cycle_features.csv
data/processed/unified_phenotype/fraiwan/fraiwan_window_manifest.csv
data/processed/unified_phenotype/hf_lung_v1/hf_phenotype_manifest.csv
data/processed/unified_phenotype/icbhi_phenotype_manifest.csv

In [2]:

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent
ML_ROOT = PROJECT_ROOT / "data" / "processed" / "classical_ml"

files_to_inspect = [
    "classical_ml_model_comparison.csv",
    "final_classical_ml_comparison.csv",
    "classical_ml_selected_features.csv",
    "classical_ml_predictions.csv",
]

for filename in files_to_inspect:
    path = ML_ROOT / filename

    print("\n" + "=" * 70)
    print(filename)
    print("=" * 70)

    if not path.exists():
        print("File not found.")
        continue

    df = pd.read_csv(path)

    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print(df.head(10).to_string(index=False))

======================================================================
classical_ml_model_comparison.csv
======================================================================
Shape: (3, 8)
Columns: ['model', 'accuracy', 'balanced_accuracy', 'macro_precision', 'macro_recall', 'macro_f1', 'weighted_f1', 'roc_auc_ovr_macro']
              model  accuracy  balanced_accuracy  macro_precision  macro_recall  macro_f1  weighted_f1  roc_auc_ovr_macro
      Random Forest  0.874456           0.426495         0.370614      0.266559  0.279604     0.877536                NaN
                SVM  0.806604           0.458256         0.260503      0.286410  0.265580     0.847078                NaN
Logistic Regression  0.641509           0.411920         0.233807      0.257450  0.218218     0.745795                NaN

======================================================================
final_classical_ml_comparison.csv
======================================================================
Shape: (3, 8)
Columns: ['Model', 'Accuracy', 'Balanced Accuracy', 'Macro Precision', 'Macro Recall', 'Macro F1', 'Weighted F1', 'ROC AUC (Macro)']
              Model  Accuracy  Balanced Accuracy  Macro Precision  Macro Recall  Macro F1  Weighted F1  ROC AUC (Macro)
      Random Forest  0.874456           0.426495         0.370614      0.266559  0.279604     0.877536              NaN
                SVM  0.806604           0.458256         0.260503      0.286410  0.265580     0.847078              NaN
Logistic Regression  0.641509           0.411920         0.233807      0.257450  0.218218     0.745795              NaN

======================================================================
classical_ml_selected_features.csv
======================================================================
Shape: (33, 1)
Columns: ['feature']
           feature
  spectral_entropy
      mfcc_11_mean
zero_crossing_rate
dominant_frequency
      mfcc_13_mean
   wavelet_entropy
       mfcc_1_mean
spectral_bandwidth
  spectral_rolloff
       mfcc_5_mean

======================================================================
classical_ml_predictions.csv
======================================================================
Shape: (2756, 7)
Columns: ['patient_id', 'recording_id', 'chest_location', 'true_diagnosis', 'logistic_regression_prediction', 'svm_prediction', 'random_forest_prediction']
 patient_id recording_id chest_location true_diagnosis logistic_regression_prediction svm_prediction random_forest_prediction
        101          1b1             Al           URTI                        Healthy      Pneumonia                     URTI
        101          1b1             Al           URTI                           URTI        Healthy                     URTI
        101          1b1             Al           URTI                        Healthy        Healthy                  Healthy
        101          1b1             Al           URTI                           URTI           URTI                     URTI
        101          1b1             Al           URTI                      Pneumonia        Healthy                     URTI
        101          1b1             Al           URTI                           URTI           URTI                     URTI
        101          1b1             Al           URTI                        Healthy        Healthy                  Healthy
        101          1b1             Al           URTI                        Healthy        Healthy                     URTI
        101          1b1             Al           URTI                        Healthy        Healthy                     COPD
        101          1b1             Al           URTI                        Healthy        Healthy                     URTI

In [3]:

from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

for folder_name in ["Notebooks", "Notebooks 2"]:
    folder = PROJECT_ROOT / folder_name

    if not folder.exists():
        continue

    print(f"\n{'=' * 65}")
    print(f"NOTEBOOKS IN: {folder_name}")
    print(f"{'=' * 65}")

    for path in sorted(folder.glob("*.ipynb")):
        print(path.name)

=================================================================
NOTEBOOKS IN: Notebooks
=================================================================
01_dataset_understanding.ipynb
02_data_cleaning.ipynb
03_eda.ipynb
04_audio_preprocessing.ipynb
05_feature_engineering.ipynb
06_feature_analysis.ipynb
07_feature_selection.ipynb
08_pca_and_clustering.ipynb
09_classical_ml.ipynb
10_deep_learning_data_preparation.ipynb
11_cnn_baseline.ipynb
12_multifeature_cnn.ipynb
13_cnn_lstm_optional.ipynb
14_patient_level_prediction.ipynb
15_xai.ipynb
16_final_model_comparison.ipynb
17_Final_Artifact_Generation_and_Validation.ipynb
18_model_validation.ipynb
19_ICBHI_Sound_Phenotype_Classification.ipynb
20_Building_a_Sound_classification.ipynb

=================================================================
NOTEBOOKS IN: Notebooks 2
=================================================================
01_Data_Audit.ipynb
01_Fraiwan_Dataset_Audit.ipynb
01_HF_Lung_V1_Dataset_Audit.ipynb
02_Leakage_Safe_Preprocessing.ipynb
03_Multidataset_Phenotype_Pretraining_ICBHI_Disease.ipynb
04_ICBHI_Disease_Transfer_Learning.ipynb
05_Lightweight_MultiFeature_CNN.ipynb
06_Combined_Dataset_Preparation.ipynb
07_HF_Lung_V1_Validation_and_CNN.ipynb
08_Combined_ICBHI_Fraiwan_HighCapacity_CNN.ipynb
09_RBF_SVM_ICBHI_Fraiwan.ipynb

In [4]:

import json
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
source_notebook = PROJECT_ROOT / "Notebooks" / "09_classical_ml.ipynb"

with source_notebook.open("r", encoding="utf-8") as f:
    notebook_data = json.load(f)

print("Notebook:", source_notebook.name)
print("Total cells:", len(notebook_data["cells"]))

for i, cell in enumerate(notebook_data["cells"]):
    if cell.get("cell_type") != "code":
        continue

    source = "".join(cell.get("source", []))
    keywords = [
        "SVC", "svm", "GridSearchCV",
        "StandardScaler", "class_weight",
        "train_test_split", "GroupShuffleSplit",
        "StratifiedGroupKFold"
    ]

    if any(word.lower() in source.lower() for word in keywords):
        print(f"\n{'=' * 65}")
        print(f"CELL {i}")
        print("=" * 65)
        print(source[:7000])

Notebook: 09_classical_ml.ipynb
Total cells: 24

=================================================================
CELL 1
=================================================================

required_objects = [
    "PROJECT_ROOT",
    "train_df",
    "test_df",
    "selected_features_df",
    "selected_feature_names",
    "X_train",
    "X_test",
    "scaler",
    "X_train_scaled",
    "X_test_scaled",
    "label_encoder",
    "y_train",
    "y_test",
    "logistic_model",
    "svm_model",
    "rf_model",
]

status = []

for name in required_objects:
    exists = name in globals()
    obj = globals().get(name) if exists else None

    status.append({
        "variable": name,
        "available": exists,
        "type": type(obj).__name__ if exists else "NOT AVAILABLE",
    })

import pandas as pd
display(pd.DataFrame(status))


=================================================================
CELL 2
=================================================================
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print("Imports completed.")

=================================================================
CELL 9
=================================================================
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape :", X_test_scaled.shape)

print("\nTraining scaled mean:")
print(np.mean(X_train_scaled, axis=0)[:10])

print("\nTraining scaled standard deviation:")
print(np.std(X_train_scaled, axis=0)[:10])

=================================================================
CELL 10
=================================================================
logistic_model = LogisticRegression(
    max_iter=3000,
    class_weight="balanced",
    random_state=42
)

logistic_model.fit(X_train_scaled, y_train)

logistic_predictions = logistic_model.predict(X_test_scaled)
logistic_probabilities = logistic_model.predict_proba(X_test_scaled)

print("Logistic Regression training completed.")

=================================================================
CELL 11
=================================================================
svm_model = SVC(
    kernel="rbf",
    class_weight="balanced",
    probability=True,
    random_state=42
)

svm_model.fit(X_train_scaled, y_train)

svm_predictions = svm_model.predict(X_test_scaled)
svm_probabilities = svm_model.predict_proba(X_test_scaled)

print("SVM training completed.")

=================================================================
CELL 12
=================================================================
rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)
rf_probabilities = rf_model.predict_proba(X_test)

print("Random Forest training completed.")

=================================================================
CELL 13
=================================================================

required = [
    "train_df",
    "test_df",
    "selected_features_df",
    "selected_feature_names",
    "scaler",
    "label_encoder",
    "logistic_model",
    "svm_model",
    "rf_model",
]

missing = [name for name in required if name not in globals()]

if missing:
    raise RuntimeError(f"Missing variables: {missing}")

print("Training objects are available.")
print("Training rows:", len(train_df))
print("Test rows:", len(test_df))
print("Selected features:", len(selected_feature_names))
print("Classes:", list(label_encoder.classes_))

assert len(train_df) == 4142, "Unexpected training row count"
assert len(test_df) == 2756, "Unexpected test row count"
assert len(selected_feature_names) == 33, "Unexpected feature count"


=================================================================
CELL 14
=================================================================

from pathlib import Path
import json
import joblib
import sklearn
import pandas as pd

# Resolve the project root using the existing notebook variable.
project_root = Path(PROJECT_ROOT)
save_dir = project_root / "models" / "traditional_ml"
save_dir.mkdir(parents=True, exist_ok=True)

# Save the fitted estimators.
models_to_save = {
    "logistic_regression": logistic_model,
    "svm": svm_model,
    "random_forest": rf_model,
}

for model_name, model in models_to_save.items():
    output_path = save_dir / f"{model_name}.joblib"
    joblib.dump(model, output_path)
    print(f"Saved {model_name}: {output_path}")

# Save the shared preprocessing objects.
joblib.dump(scaler, save_dir / "scaler.joblib")
joblib.dump(label_encoder, save_dir / "label_encoder.joblib")

# Save feature order and metadata.
metadata = {
    "project": "Respiratory Disease Classification",
    "source_notebook": "notebooks/09_classical_ml.ipynb",
    "training_rows": int(len(train_df)),
    "test_rows": int(len(test_df)),
    "feature_count": int(len(selected_feature_names)),
    "selected_feature_names": list(selected_feature_names),
    "class_names": [str(c) for c in label_encoder.classes_],
    "scaler_used": {
        "logistic_regression": True,
        "svm": True,
        "random_forest": False,
    },
    "training_split": "Existing official_split; unchanged",
    "sklearn_version": sklearn.__version__,
    "models": {
        "logistic_regression": {
            "file": "logistic_regression.joblib",
            "class": type(logistic_model).__name__,
            "parameters": logistic_model.get_params(),
        },
        "svm": {
            "file": "svm.joblib",
            "class": type(svm_model).__name__,
            "parameters": svm_model.get_params(),
        },
        "random_forest": {
            "file": "random_forest.joblib",
            "class": type(rf_model).__name__,
            "parameters": rf_model.get_params(),
        },
    },
}

with open(save_dir / "classical_ml_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2, default=str)

# Save the ordered feature list separately for convenient inspection.
with open(save_dir / "selected_features.json", "w") as f:
    json.dump(list(selected_feature_names), f, indent=2)

print("\nSaved preprocessing and metadata.")
print("Output directory:", save_dir)
print("Files:")
for path in sorted(save_dir.iterdir()):
    if path.is_file():
        print(f"  {path.name} ({path.stat().st_size:,} bytes)")


=================================================================
CELL 15
=================================================================

import numpy as np
import joblib

saved_logistic = joblib.load(save_dir / "logistic_regression.joblib")
saved_svm = joblib.load(save_dir / "svm.joblib")
saved_rf = joblib.load(save_dir / "random_forest.joblib")

saved_scaler = joblib.load(save_dir / "scaler.joblib")
saved_encoder = joblib.load(save_dir / "label_encoder.joblib")

# Preserve the training-time feature representations.
X_test_raw = X_test
X_test_scaled_saved = saved_scaler.transform(X_test_raw)

checks = {
    "Logistic Regression": np.array_equal(
        saved_logistic.predict(X_test_scaled_saved),
        logistic_model.predict(X_test_scaled),
    ),
    "SVM": np.array_equal(
        saved_svm.predict(X_test_scaled_saved),
        svm_model.predict(X_test_scaled),
    ),
    "Random Forest": np.array_equal(
        saved_rf.predict(X_test_raw),
        rf_model.predict(X_test),
    ),
}

assert np.array_equal(
    saved_encoder.classes_, label_encoder.classes_
), "Label encoder classes do not match"

assert all(checks.values()), f"Prediction mismatch: {checks}"

print("PASS — saved models reload correctly.")
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL'} — {name} predictions match")

print("PASS — scaler and label encoder reload correctly.")


=================================================================
CELL 18
=================================================================
logistic_results = evaluate_model(
    "Logistic Regression",
    y_test,
    logistic_predictions,
    logistic_probabilities,
    class_names
)

svm_results = evaluate_model(
    "SVM",
    y_test,
    svm_predictions,
    svm_probabilities,
    class_names
)

rf_results = evaluate_model(
    "Random Forest",
    y_test,
    rf_predictions,
    rf_probabilities,
    class_names
)

=================================================================
CELL 19
=================================================================
# ============================================================
# NOTEBOOK 09 — STEP 2
# CLASSICAL ML MODEL COMPARISON
# ============================================================

results_df = pd.DataFrame([
    logistic_results,
    svm_results,
    rf_results
])

results_df = results_df[
    [
        "model",
        "accuracy",
        "balanced_accuracy",
        "macro_precision",
        "macro_recall",
        "macro_f1",
        "weighted_f1",
        "roc_auc_ovr_macro"
    ]
].sort_values(
    by="macro_f1",
    ascending=False
).reset_index(drop=True)

print("=" * 80)
print("CLASSICAL MACHINE LEARNING MODEL COMPARISON")
print("=" * 80)

display(
    results_df.style.format({
        "accuracy": "{:.4f}",
        "balanced_accuracy": "{:.4f}",
        "macro_precision": "{:.4f}",
        "macro_recall": "{:.4f}",
        "macro_f1": "{:.4f}",
        "weighted_f1": "{:.4f}",
        "roc_auc_ovr_macro": "{:.4f}"
    })
)

print("\nTest-set disease support:")
print(
    test_df["diagnosis"]
    .value_counts()
    .reindex(class_names, fill_value=0)
)

=================================================================
CELL 20
=================================================================
# ============================================================
# NOTEBOOK 09 — STEP 3
# CONFUSION MATRICES AND PER-DISEASE PERFORMANCE
# ============================================================

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

predictions_dict = {
    "Logistic Regression": logistic_predictions,
    "SVM": svm_predictions,
    "Random Forest": rf_predictions
}

# ------------------------------------------------------------
# 1. Confusion matrices
# ------------------------------------------------------------

for model_name, predictions in predictions_dict.items():

    cm = confusion_matrix(
        y_test,
        predictions,
        labels=np.arange(len(class_names))
    )

    plt.figure(figsize=(9, 7))

    plt.imshow(cm, aspect="auto")
    plt.colorbar()

    plt.xticks(
        range(len(class_names)),
        class_names,
        rotation=45,
        ha="right"
    )

    plt.yticks(
        range(len(class_names)),
        class_names
    )

    plt.xlabel("Predicted Disease")
    plt.ylabel("True Disease")
    plt.title(f"{model_name} — Confusion Matrix")

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(
                j,
                i,
                cm[i, j],
                ha="center",
                va="center"
            )

    plt.tight_layout()
    plt.show()


# ------------------------------------------------------------
# 2. Per-disease metrics for all models
# ------------------------------------------------------------

per_class_rows = []

for model_name, predictions in predictions_dict.items():

    report = classification_report(
        y_test,
        predictions,
        labels=np.arange(len(class_names)),
        target_names=class_names,
        output_dict=True,
        zero_division=0
    )

    for disease in class_names:

        per_class_rows.append({
            "model": model_name,
            "disease": disease,
            "precision": report[disease]["precision"],
            "recall": report[disease]["recall"],
            "f1_score": report[disease]["f1-score"],
            "support": int(report[disease]["support"])
        })

per_class_results_df = pd.DataFrame(per_class_rows)

print("=" * 80)
print("PER-DISEASE CLASSIFICATION PERFORMANCE")
print("=" * 80)

display(
    per_class_results_df.style.format({
        "precision": "{:.4f}",
        "recall": "{:.4f}",
        "f1_score": "{:.4f}"
    })
)


# ------------------------------------------------------------
# 3. Compare macro F1 by disease
# ------------------------------------------------------------

f1_comparison = per_class_results_df.pivot(
    index="disease",
    columns="model",
    values="f1_score"
)

print("\n" + "=" * 80)
print("F1-SCORE BY DISEASE")
print("=" * 80)

display(
    f1_comparison.style.format("{:.4f}")
)

=================================================================
CELL 22
=================================================================
# ============================================================
# NOTEBOOK 09 — STEP 5
# SAVE ALL CLASSICAL ML RESULTS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. CREATE OUTPUT DIRECTORY
# ------------------------------------------------------------

CLASSICAL_ML_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "classical_ml"
)

CLASSICAL_ML_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 2. SAVE MODEL COMPARISON
# ------------------------------------------------------------

results_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_model_comparison.csv",
    index=False
)


# ------------------------------------------------------------
# 3. SAVE PER-DISEASE RESULTS
# ------------------------------------------------------------

per_class_results_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_per_disease_results.csv",
    index=False
)


# ------------------------------------------------------------
# 4. SAVE RANDOM FOREST FEATURE IMPORTANCE
# ------------------------------------------------------------

rf_importance_df.to_csv(
    CLASSICAL_ML_DIR / "random_forest_feature_importance.csv",
    index=False
)


# ------------------------------------------------------------
# 5. SAVE FEATURE-GROUP IMPORTANCE
# ------------------------------------------------------------

group_importance.reset_index().to_csv(
    CLASSICAL_ML_DIR / "random_forest_feature_group_importance.csv",
    index=False
)


# ------------------------------------------------------------
# 6. SAVE SELECTED FEATURES USED BY THE MODELS
# ------------------------------------------------------------

pd.DataFrame({
    "feature": selected_feature_names
}).to_csv(
    CLASSICAL_ML_DIR / "classical_ml_selected_features.csv",
    index=False
)


# ------------------------------------------------------------
# 7. SAVE MODEL PREDICTIONS
# ------------------------------------------------------------

prediction_df = pd.DataFrame({
    "patient_id": test_df["patient_id"].values,
    "recording_id": test_df["recording_id"].values,
    "chest_location": test_df["chest_location"].values,
    "true_diagnosis": test_df["diagnosis"].values,

    "logistic_regression_prediction":
        label_encoder.inverse_transform(logistic_predictions),

    "svm_prediction":
        label_encoder.inverse_transform(svm_predictions),

    "random_forest_prediction":
        label_encoder.inverse_transform(rf_predictions)
})

prediction_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_predictions.csv",
    index=False
)


# ------------------------------------------------------------
# 8. FINAL VALIDATION
# ------------------------------------------------------------

saved_files = sorted(
    CLASSICAL_ML_DIR.glob("*.csv")
)

print("=" * 80)
print("NOTEBOOK 09 — CLASSICAL ML RESULTS SAVED")
print("=" * 80)

for file_path in saved_files:
    print(file_path.name)

print("\nOutput directory:")
print(CLASSICAL_ML_DIR)

print("\nModel comparison:")
display(results_df)

print("\nBest model by macro F1:")
best_model = results_df.iloc[0]

print("Model:", best_model["model"])
print("Macro F1:", round(best_model["macro_f1"], 4))
print("Balanced Accuracy:", round(
    best_model["balanced_accuracy"], 4
))
print("Accuracy:", round(
    best_model["accuracy"], 4
))

print("\n" + "=" * 80)
print("NOTEBOOK 09 VALIDATION COMPLETE")
print("=" * 80)

In [5]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

paths_to_check = [
    PROJECT_ROOT / "data" / "processed" / "features" /
        "respiratory_cycle_features.csv",
    PROJECT_ROOT / "data" / "processed" / "classical_ml" /
        "classical_ml_selected_features.csv",
    PROJECT_ROOT / "data" / "processed" / "deep_learning" /
        "train_manifest.csv",
    PROJECT_ROOT / "data" / "processed" / "deep_learning" /
        "test_manifest.csv",
    PROJECT_ROOT / "data" / "processed" /
        "unified_phenotype" / "icbhi_phenotype_manifest.csv",
]

for path in paths_to_check:
    print(f"\n{path.relative_to(PROJECT_ROOT)}")
    print("Exists:", path.exists())

    if path.exists() and path.suffix == ".csv":
        import pandas as pd
        df = pd.read_csv(path, nrows=5)
        print("Columns:", df.columns.tolist())
        print(df.head(2).to_string(index=False))

data/processed/features/respiratory_cycle_features.csv
Exists: True
Columns: ['patient_id', 'recording_id', 'chest_location', 'acquisition_mode', 'equipment', 'cycle_number', 'start_time', 'end_time', 'sound_label', 'crackles', 'wheezes', 'diagnosis', 'processed_path', 'mean', 'std', 'variance', 'rms', 'max', 'min', 'peak_to_peak', 'median', 'skewness', 'kurtosis', 'energy', 'zero_crossing_rate', 'spectral_centroid', 'spectral_bandwidth', 'spectral_rolloff', 'spectral_flatness', 'spectral_energy', 'dominant_frequency', 'spectral_entropy', 'band_energy_0_500', 'band_energy_500_1000', 'band_energy_1000_1500', 'band_energy_1500_2000', 'mfcc_1_mean', 'mfcc_2_mean', 'mfcc_3_mean', 'mfcc_4_mean', 'mfcc_5_mean', 'mfcc_6_mean', 'mfcc_7_mean', 'mfcc_8_mean', 'mfcc_9_mean', 'mfcc_10_mean', 'mfcc_11_mean', 'mfcc_12_mean', 'mfcc_13_mean', 'wavelet_energy', 'wavelet_entropy', 'wavelet_std']
 patient_id recording_id chest_location acquisition_mode equipment  cycle_number  start_time  end_time sound_label  crackles  wheezes diagnosis                  processed_path      mean      std  variance      rms      max       min  peak_to_peak    median  skewness  kurtosis     energy  zero_crossing_rate  spectral_centroid  spectral_bandwidth  spectral_rolloff  spectral_flatness  spectral_energy  dominant_frequency  spectral_entropy  band_energy_0_500  band_energy_500_1000  band_energy_1000_1500  band_energy_1500_2000  mfcc_1_mean  mfcc_2_mean  mfcc_3_mean  mfcc_4_mean  mfcc_5_mean  mfcc_6_mean  mfcc_7_mean  mfcc_8_mean  mfcc_9_mean  mfcc_10_mean  mfcc_11_mean  mfcc_12_mean  mfcc_13_mean  wavelet_energy  wavelet_entropy  wavelet_std
        101          1b1             Al               sc  Meditron             1       0.036     0.579      Normal         0        0      URTI audio/cycles/101/1b1_Al_001.wav -0.008510 0.223403  0.049909 0.223565 0.999969 -0.486725      1.486694 -0.016464  0.698439  2.107791 108.559375            0.008594          85.291204          172.467679        150.275735           0.000955     42084.371118             15.6250          2.379418           0.999853              0.000054               0.000035               0.000058  -437.956573   145.963989    62.398502    38.109188    24.845795    30.785465    14.649715    13.271879    15.322943      4.408390      9.810836     11.595978      6.332477      110.760926         0.062777     0.224449
        101          1b1             Al               sc  Meditron             2       0.579     2.450      Normal         0        0      URTI audio/cycles/101/1b1_Al_002.wav -0.002198 0.186333  0.034720 0.186346 0.999969 -0.506805      1.506775 -0.009888  1.244139  3.901894 259.881487            0.010872          70.776118          153.590198        101.165254           0.000273    105864.901312              7.8125          2.508823           0.999940              0.000041               0.000010               0.000009  -462.323608   145.272705    69.182137    42.136631    26.606405    26.884298    11.704497    17.665747    14.362599      8.428231      8.835912     10.312641      6.039036      263.467394         0.090006     0.187299

data/processed/classical_ml/classical_ml_selected_features.csv
Exists: True
Columns: ['feature']
         feature
spectral_entropy
    mfcc_11_mean

data/processed/deep_learning/train_manifest.csv
Exists: True
Columns: ['patient_id', 'recording_id', 'chest_location', 'diagnosis', 'disease_label', 'official_split', 'audio_path']
 patient_id recording_id chest_location diagnosis  disease_label official_split                                                                                        audio_path
        103          2b2             Ar    Asthma              0          train /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/103/2b2_Ar_001.wav
        103          2b2             Ar    Asthma              0          train /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/103/2b2_Ar_002.wav

data/processed/deep_learning/test_manifest.csv
Exists: True
Columns: ['patient_id', 'recording_id', 'chest_location', 'diagnosis', 'disease_label', 'official_split', 'audio_path']
 patient_id recording_id chest_location diagnosis  disease_label official_split                                                                                        audio_path
        101          1b1             Al      URTI              7           test /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/101/1b1_Al_001.wav
        101          1b1             Al      URTI              7           test /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/101/1b1_Al_002.wav

data/processed/unified_phenotype/icbhi_phenotype_manifest.csv
Exists: True
Columns: ['chest_location', 'acquisition_mode', 'equipment', 'cycle_number', 'start_time', 'end_time', 'sound_label', 'crackles', 'wheezes', 'processed_path', 'mean', 'std', 'variance', 'rms', 'max', 'min', 'peak_to_peak', 'median', 'skewness', 'kurtosis', 'energy', 'zero_crossing_rate', 'spectral_centroid', 'spectral_bandwidth', 'spectral_rolloff', 'spectral_flatness', 'spectral_energy', 'dominant_frequency', 'spectral_entropy', 'band_energy_0_500', 'band_energy_500_1000', 'band_energy_1000_1500', 'band_energy_1500_2000', 'mfcc_1_mean', 'mfcc_2_mean', 'mfcc_3_mean', 'mfcc_4_mean', 'mfcc_5_mean', 'mfcc_6_mean', 'mfcc_7_mean', 'mfcc_8_mean', 'mfcc_9_mean', 'mfcc_10_mean', 'mfcc_11_mean', 'mfcc_12_mean', 'mfcc_13_mean', 'wavelet_energy', 'wavelet_entropy', 'wavelet_std', 'audio_key', 'cnn_split', 'official_split', 'patient_id', 'recording_id', 'diagnosis', 'disease_label', 'phenotype_label', 'split', 'dataset', 'label_granularity', 'processed_audio_path']
chest_location acquisition_mode equipment  cycle_number  start_time  end_time sound_label  crackles  wheezes                  processed_path      mean      std  variance      rms      max       min  peak_to_peak    median  skewness  kurtosis     energy  zero_crossing_rate  spectral_centroid  spectral_bandwidth  spectral_rolloff  spectral_flatness  spectral_energy  dominant_frequency  spectral_entropy  band_energy_0_500  band_energy_500_1000  band_energy_1000_1500  band_energy_1500_2000  mfcc_1_mean  mfcc_2_mean  mfcc_3_mean  mfcc_4_mean  mfcc_5_mean  mfcc_6_mean  mfcc_7_mean  mfcc_8_mean  mfcc_9_mean  mfcc_10_mean  mfcc_11_mean  mfcc_12_mean  mfcc_13_mean  wavelet_energy  wavelet_entropy  wavelet_std                                                                                         audio_key cnn_split official_split  patient_id recording_id diagnosis  disease_label phenotype_label split dataset label_granularity            processed_audio_path
            Al               sc  Meditron             1       0.036     0.579      Normal         0        0 audio/cycles/101/1b1_Al_001.wav -0.008510 0.223403  0.049909 0.223565 0.999969 -0.486725      1.486694 -0.016464  0.698439  2.107791 108.559375            0.008594          85.291204          172.467679        150.275735           0.000955     42084.371118             15.6250          2.379418           0.999853              0.000054               0.000035               0.000058  -437.956573   145.963989    62.398502    38.109188    24.845795    30.785465    14.649715    13.271879    15.322943      4.408390      9.810836     11.595978      6.332477      110.760926         0.062777     0.224449 /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/101/1b1_Al_001.wav      test           test         101          1b1      URTI              7          Normal  test   ICBHI respiratory_cycle audio/cycles/101/1b1_Al_001.wav
            Al               sc  Meditron             2       0.579     2.450      Normal         0        0 audio/cycles/101/1b1_Al_002.wav -0.002198 0.186333  0.034720 0.186346 0.999969 -0.506805      1.506775 -0.009888  1.244139  3.901894 259.881487            0.010872          70.776118          153.590198        101.165254           0.000273    105864.901312              7.8125          2.508823           0.999940              0.000041               0.000010               0.000009  -462.323608   145.272705    69.182137    42.136631    26.606405    26.884298    11.704497    17.665747    14.362599      8.428231      8.835912     10.312641      6.039036      263.467394         0.090006     0.187299 /Users/vs/Sem 5/Respiratory-Disease-Classification/data/processed/audio/cycles/101/1b1_Al_002.wav      test           test         101          1b1      URTI              7          Normal  test   ICBHI respiratory_cycle audio/cycles/101/1b1_Al_002.wav

In [6]:

from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent

FEATURES_PATH = (
    PROJECT_ROOT / "data" / "processed" / "features"
    / "respiratory_cycle_features.csv"
)

TRAIN_MANIFEST_PATH = (
    PROJECT_ROOT / "data" / "processed" / "deep_learning"
    / "train_manifest.csv"
)

TEST_MANIFEST_PATH = (
    PROJECT_ROOT / "data" / "processed" / "deep_learning"
    / "test_manifest.csv"
)

SELECTED_FEATURES_PATH = (
    PROJECT_ROOT / "data" / "processed" / "classical_ml"
    / "classical_ml_selected_features.csv"
)

features_df = pd.read_csv(FEATURES_PATH)
train_manifest = pd.read_csv(TRAIN_MANIFEST_PATH)
test_manifest = pd.read_csv(TEST_MANIFEST_PATH)

selected_features = pd.read_csv(
    SELECTED_FEATURES_PATH
)["feature"].tolist()

print("Feature-table rows:", len(features_df))
print("Selected features:", len(selected_features))
print("Training manifest rows:", len(train_manifest))
print("Test manifest rows:", len(test_manifest))

print("\nTrain/test patient overlap:")
train_patients = set(train_manifest["patient_id"].astype(str))
test_patients = set(test_manifest["patient_id"].astype(str))
overlap = train_patients & test_patients

print("Overlapping patients:", len(overlap))
if overlap:
    print("Examples:", sorted(overlap)[:10])

print("\nTraining diagnoses:")
print(train_manifest["diagnosis"].value_counts().sort_index())

print("\nTest diagnoses:")
print(test_manifest["diagnosis"].value_counts().sort_index())

missing_features = [
    feature for feature in selected_features
    if feature not in features_df.columns
]
print("\nMissing selected features:", missing_features)

print("\nAvailable split columns:", train_manifest.columns.tolist())

assert not missing_features, "Some selected features are absent."
assert not overlap, "Patient leakage detected between train and test."

print("\nAudit completed. No model has been trained.")

Feature-table rows: 6898
Selected features: 33
Training manifest rows: 4142
Test manifest rows: 2756

Train/test patient overlap:
Overlapping patients: 2
Examples: ['156', '218']

Training diagnoses:
diagnosis
Asthma               6
Bronchiectasis      90
Bronchiolitis       74
COPD              3337
Healthy            147
LRTI                32
Pneumonia          285
URTI               171
Name: count, dtype: int64

Test diagnoses:
diagnosis
Bronchiectasis      14
Bronchiolitis       86
COPD              2409
Healthy            175
URTI                72
Name: count, dtype: int64

Missing selected features: []

Available split columns: ['patient_id', 'recording_id', 'chest_location', 'diagnosis', 'disease_label', 'official_split', 'audio_path']

AssertionError: Patient leakage detected between train and test.

In [7]:
# Inspect patient overlap and official split assignments.
# This cell does not modify any files or train a model.

print("=== OVERLAPPING PATIENTS ===")

for patient_id in sorted(overlap):
    print(f"\nPatient ID: {patient_id}")

    print("\nTraining manifest records:")
    display(
        train_manifest[
            train_manifest["patient_id"].astype(str) == patient_id
        ][
            ["patient_id", "recording_id", "chest_location",
             "diagnosis", "disease_label", "official_split", "audio_path"]
        ].head(15)
    )

    print("\nTest manifest records:")
    display(
        test_manifest[
            test_manifest["patient_id"].astype(str) == patient_id
        ][
            ["patient_id", "recording_id", "chest_location",
             "diagnosis", "disease_label", "official_split", "audio_path"]
        ].head(15)
    )

print("\n=== OFFICIAL SPLIT COUNTS ===")
print("Training:")
print(train_manifest["official_split"].value_counts(dropna=False))

print("\nTest:")
print(test_manifest["official_split"].value_counts(dropna=False))

=== OVERLAPPING PATIENTS ===

Patient ID: 156

Training manifest records:

,patient_id,recording_id,chest_location,diagnosis,disease_label,official_split,audio_path
1873,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1874,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1875,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1876,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1877,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1878,156,2b3,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1879,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1880,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1881,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1882,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1883,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1884,156,2b3,Ll,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1885,156,2b3,Pr,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1886,156,2b3,Pr,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1887,156,2b3,Pr,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...

Test manifest records:

,patient_id,recording_id,chest_location,diagnosis,disease_label,official_split,audio_path
1023,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1024,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1025,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1026,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1027,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1028,156,2b3,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1029,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1030,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1031,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1032,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1033,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1034,156,2b3,Lr,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1035,156,2b3,Pl,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1036,156,2b3,Pl,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
1037,156,2b3,Pl,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...

Patient ID: 218

Training manifest records:

,patient_id,recording_id,chest_location,diagnosis,disease_label,official_split,audio_path
3915,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3916,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3917,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3918,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3919,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3920,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3921,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3922,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3923,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3924,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3925,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3926,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3927,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3928,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
3929,218,1b1,Ar,COPD,3,train,/Users/vs/Sem 5/Respiratory-Disease-Classifica...

Test manifest records:

,patient_id,recording_id,chest_location,diagnosis,disease_label,official_split,audio_path
2608,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2609,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2610,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2611,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2612,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2613,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2614,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2615,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2616,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2617,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2618,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2619,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2620,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2621,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...
2622,218,1b1,Al,COPD,3,test,/Users/vs/Sem 5/Respiratory-Disease-Classifica...

=== OFFICIAL SPLIT COUNTS ===
Training:
official_split
train    4142
Name: count, dtype: int64

Test:
official_split
test    2756
Name: count, dtype: int64

In [8]:
# Inspect feature-table identity and split consistency.
# Read-only: no training and no file modifications.

identity_cols = [
    "patient_id",
    "recording_id",
    "chest_location",
    "diagnosis",
]

print("=== FEATURE TABLE: OVERLAPPING PATIENTS ===")

for patient_id in sorted(overlap):
    patient_rows = features_df[
        features_df["patient_id"].astype(str) == patient_id
    ]

    print(f"\nPatient {patient_id}")
    print("Feature-table rows:", len(patient_rows))

    display(
        patient_rows[
            identity_cols + [
                col for col in ["cycle_number", "sound_label"]
                if col in patient_rows.columns
            ]
        ].drop_duplicates().head(30)
    )

print("\n=== RECORDING-LOCATION COMBINATIONS IN EACH SPLIT ===")

train_keys = train_manifest[identity_cols].drop_duplicates()
test_keys = test_manifest[identity_cols].drop_duplicates()

key_cols = ["patient_id", "recording_id", "chest_location"]

train_recording_keys = train_keys[key_cols].drop_duplicates()
test_recording_keys = test_keys[key_cols].drop_duplicates()

shared_recordings = train_recording_keys.merge(
    test_recording_keys,
    on=key_cols,
    how="inner",
)

print("Shared patient-recording-location combinations:",
      len(shared_recordings))
display(shared_recordings.head(30))

print("\n=== MANIFEST DUPLICATE CHECK ===")
print("Train duplicate identity rows:",
      train_manifest.duplicated(identity_cols).sum())
print("Test duplicate identity rows:",
      test_manifest.duplicated(identity_cols).sum())

=== FEATURE TABLE: OVERLAPPING PATIENTS ===

Patient 156
Feature-table rows: 130

,patient_id,recording_id,chest_location,diagnosis,cycle_number,sound_label
2896,156,2b3,Al,COPD,1,Both
2897,156,2b3,Al,COPD,2,Both
2898,156,2b3,Al,COPD,3,Crackles
2899,156,2b3,Al,COPD,4,Both
2900,156,2b3,Al,COPD,5,Both
2901,156,2b3,Al,COPD,6,Both
2902,156,2b3,Ar,COPD,1,Wheezes
2903,156,2b3,Ar,COPD,2,Both
2904,156,2b3,Ar,COPD,3,Crackles
2905,156,2b3,Ar,COPD,4,Normal
2906,156,2b3,Ar,COPD,5,Crackles
2907,156,2b3,Ar,COPD,6,Crackles
2908,156,2b3,Ll,COPD,1,Both
2909,156,2b3,Ll,COPD,2,Both
2910,156,2b3,Ll,COPD,3,Both
2911,156,2b3,Ll,COPD,4,Both
2912,156,2b3,Ll,COPD,5,Both
2913,156,2b3,Ll,COPD,6,Both
2914,156,2b3,Lr,COPD,1,Both
2915,156,2b3,Lr,COPD,2,Both
2916,156,2b3,Lr,COPD,3,Crackles
2917,156,2b3,Lr,COPD,4,Crackles
2918,156,2b3,Lr,COPD,5,Crackles
2919,156,2b3,Lr,COPD,6,Both
2920,156,2b3,Pl,COPD,1,Both
2921,156,2b3,Pl,COPD,2,Both
2922,156,2b3,Pl,COPD,3,Crackles
2923,156,2b3,Pl,COPD,4,Both
2924,156,2b3,Pl,COPD,5,Both
2925,156,2b3,Pl,COPD,6,Both

Patient 218
Feature-table rows: 107

,patient_id,recording_id,chest_location,diagnosis,cycle_number,sound_label
6523,218,1b1,Al,COPD,1,Normal
6524,218,1b1,Al,COPD,2,Normal
6525,218,1b1,Al,COPD,3,Normal
6526,218,1b1,Al,COPD,4,Normal
6527,218,1b1,Al,COPD,5,Wheezes
6528,218,1b1,Al,COPD,6,Crackles
6529,218,1b1,Al,COPD,7,Crackles
6530,218,1b1,Al,COPD,8,Crackles
6531,218,1b1,Al,COPD,9,Crackles
6532,218,1b1,Al,COPD,10,Both
6533,218,1b1,Al,COPD,11,Both
6534,218,1b1,Al,COPD,12,Both
6535,218,1b1,Al,COPD,13,Both
6536,218,1b1,Al,COPD,14,Normal
6537,218,1b1,Al,COPD,15,Both
6538,218,1b1,Ar,COPD,1,Both
6539,218,1b1,Ar,COPD,2,Both
6540,218,1b1,Ar,COPD,3,Both
6541,218,1b1,Ar,COPD,4,Normal
6542,218,1b1,Ar,COPD,5,Wheezes
6543,218,1b1,Ar,COPD,6,Both
6544,218,1b1,Ar,COPD,7,Both
6545,218,1b1,Ar,COPD,8,Both
6546,218,1b1,Ar,COPD,9,Crackles
6547,218,1b1,Ar,COPD,10,Crackles
6548,218,1b1,Ar,COPD,11,Both
6549,218,1b1,Ar,COPD,12,Both
6550,218,1b1,Ar,COPD,13,Both
6551,218,1b1,Ar,COPD,14,Both
6552,218,1b1,Ar,COPD,15,Both

=== RECORDING-LOCATION COMBINATIONS IN EACH SPLIT ===
Shared patient-recording-location combinations: 0

Empty DataFrame
Columns: [patient_id, recording_id, chest_location]
Index: []

=== MANIFEST DUPLICATE CHECK ===
Train duplicate identity rows: 3603
Test duplicate identity rows: 2375

In [9]:
from pathlib import Path
import json

notebook_dirs = [
    PROJECT_ROOT / "Notebooks",
    PROJECT_ROOT / "Notebooks 2",
]

search_terms = [
    "train_manifest.csv",
    "test_manifest.csv",
    "official_split",
    "GroupShuffleSplit",
    "GroupKFold",
    "train_test_split",
]

print("=== NOTEBOOK SPLIT-GENERATION SEARCH ===")

for notebook_dir in notebook_dirs:
    if not notebook_dir.exists():
        continue

    for notebook_path in sorted(notebook_dir.glob("*.ipynb")):
        try:
            with open(notebook_path, "r", encoding="utf-8") as f:
                notebook = json.load(f)
        except Exception:
            continue

        for cell_index, cell in enumerate(notebook.get("cells", [])):
            if cell.get("cell_type") != "code":
                continue

            source = "".join(cell.get("source", []))

            matched_terms = [
                term for term in search_terms
                if term.lower() in source.lower()
            ]

            if matched_terms:
                print(
                    f"\nNotebook: {notebook_path.name} | "
                    f"Cell: {cell_index} | "
                    f"Matches: {matched_terms}"
                )
                print(source[:1800])
                print("-" * 70)

=== NOTEBOOK SPLIT-GENERATION SEARCH ===

Notebook: 01_dataset_understanding.ipynb | Cell: 124 | Matches: ['official_split']
official_split_path = RAW_DATA_DIR / "metadata" / "official_split.csv"

official_split_df = pd.read_csv(
    official_split_path,
    sep=None,
    engine="python"
)

print("Rows:", len(official_split_df))
print("Columns:", official_split_df.columns.tolist())

display(official_split_df.head())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 125 | Matches: ['official_split']
print(official_split_df.iloc[:, -1].value_counts())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 126 | Matches: ['official_split']
print("Unique recordings:", official_split_df.iloc[:, 0].nunique())
print("Duplicate rows:", official_split_df.duplicated().sum())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 127 | Matches: ['official_split']
official_split_df = official_split_df.copy()

official_split_df["filename"] = (
    official_split_df.iloc[:, 0].astype(str) + ".wav"
)

print("Official split recordings:", len(official_split_df))
display(official_split_df.head())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 128 | Matches: ['official_split']
our_recordings = set(
    Path(path).name
    for path in recordings_df["wav_path"]
)

official_recordings = set(
    official_split_df["filename"]
)

missing_from_split = our_recordings - official_recordings
missing_from_dataset = official_recordings - our_recordings

print("Our WAV recordings:", len(our_recordings))
print("Official split recordings:", len(official_recordings))
print("WAVs missing from official split:", len(missing_from_split))
print("Official recordings missing from WAV dataset:", len(missing_from_dataset))
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 133 | Matches: ['official_split']
official_split_df.loc[
    official_split_df.iloc[:, 0] == "226_1b1_Pl_sc_Meditron",
    official_split_df.columns[0]
] = "226_1b1_Pl_sc_LittC2SE"

print(
    official_split_df[
        official_split_df.iloc[:, 0].str.startswith("226_1b1_Pl_sc_")
    ]
)
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 134 | Matches: ['official_split']
official_split_df["filename"] = (
    official_split_df.iloc[:, 0].astype(str) + ".wav"
)

official_recordings = set(official_split_df["filename"])

missing_from_split = our_recordings - official_recordings
missing_from_dataset = official_recordings - our_recordings

print("Our WAV recordings:", len(our_recordings))
print("Official split recordings:", len(official_recordings))
print("WAVs missing from official split:", len(missing_from_split))
print("Official recordings missing from WAV dataset:", len(missing_from_dataset))
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 135 | Matches: ['official_split']
split_column = official_split_df.columns[1]

split_lookup = official_split_df[
    [official_split_df.columns[0], split_column]
].copy()

split_lookup.columns = ["recording_name", "official_split"]

recordings_df["recording_name"] = recordings_df["wav_path"].apply(
    lambda x: Path(x).name
)

recordings_df = recordings_df.merge(
    split_lookup,
    on="recording_name",
    how="left"
)

print("Recordings:", len(recordings_df))
print(
    "Missing official split labels:",
    recordings_df["official_split"].isna().sum()
)

print("\nOfficial split distribution:")
print(recordings_df["official_split"].value_counts())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 137 | Matches: ['official_split']
train_patients = set(
    recordings_df.loc[
        recordings_df["official_split"] == "train",
        "patient_id"
    ]
)

test_patients = set(
    recordings_df.loc[
        recordings_df["official_split"] == "test",
        "patient_id"
    ]
)

overlap_patients = train_patients & test_patients

print("Train patients:", len(train_patients))
print("Test patients:", len(test_patients))
print("Patients appearing in both:", len(overlap_patients))
print("Overlapping patient IDs:", sorted(overlap_patients))
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 138 | Matches: ['official_split']
recording_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "acquisition_mode",
    "equipment",
    "wav_path",
    "official_split"
]

recordings_final_df = recordings_df[recording_columns].copy()

print("Rows:", len(recordings_final_df))
print("Unique recordings:", recordings_final_df["wav_path"].nunique())
print("Missing values:")
print(recordings_final_df.isnull().sum())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 140 | Matches: ['official_split']
missing_split = recordings_df[
    recordings_df["official_split"].isna()
]

print("Recordings with missing split:",
      len(missing_split))

display(missing_split)
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 141 | Matches: ['official_split']
print("Official split columns:")
print(official_split_df.columns.tolist())

print("\nFirst 5 rows:")
display(official_split_df.head())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 142 | Matches: ['official_split']
print("Recordings columns:")
print(recordings_df.columns.tolist())

print("\nFirst 5 recording names:")
display(
    recordings_df[
        ["recording_name", "official_split"]
    ].head()
)
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 143 | Matches: ['official_split']
recordings_df = recordings_df.drop(
    columns=["official_split"],
    errors="ignore"
)
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 144 | Matches: ['official_split']
split_lookup = official_split_df[
    ["filename", "split"]
].copy()

split_lookup = split_lookup.rename(
    columns={
        "filename": "recording_name",
        "split": "official_split"
    }
)

print(split_lookup.head())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 145 | Matches: ['official_split']
recordings_df = recordings_df.merge(
    split_lookup,
    on="recording_name",
    how="left",
    validate="one_to_one"
)

print("Recordings:", len(recordings_df))
print(
    "Missing official split labels:",
    recordings_df["official_split"].isna().sum()
)

print("\nSplit distribution:")
print(recordings_df["official_split"].value_counts())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 146 | Matches: ['official_split']
recording_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "acquisition_mode",
    "equipment",
    "wav_path",
    "official_split"
]

recordings_final_df = recordings_df[recording_columns].copy()

print("Rows:", len(recordings_final_df))
print("Unique recordings:", recordings_final_df["wav_path"].nunique())

print("\nMissing values:")
print(recordings_final_df.isnull().sum())
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 148 | Matches: ['official_split']
print(
    recordings_final_df["official_split"].value_counts()
)
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 149 | Matches: ['official_split']
train_patients = set(
    recordings_final_df.loc[
        recordings_final_df["official_split"] == "train",
        "patient_id"
    ]
)

test_patients = set(
    recordings_final_df.loc[
        recordings_final_df["official_split"] == "test",
        "patient_id"
    ]
)

overlap_patients = train_patients & test_patients

print("Train patients:", len(train_patients))
print("Test patients:", len(test_patients))
print("Patients in both train and test:", len(overlap_patients))
print("Overlapping patients:", sorted(overlap_patients))
----------------------------------------------------------------------

Notebook: 01_dataset_understanding.ipynb | Cell: 151 | Matches: ['official_split']
dataset_summary = {
    "patients": patients_final_df["patient_id"].nunique(),
    "recordings": recordings_final_df["wav_path"].nunique(),
    "respiratory_cycles": len(cycles_final_df),
    "train_recordings": (
        recordings_final_df["official_split"] == "train"
    ).sum(),
    "test_recordings": (
        recordings_final_df["official_split"] == "test"
    ).sum(),
    "train_patients": len(train_patients),
    "test_patients": len(test_patients),
    "overlapping_patients": len(overlap_patients),
}

dataset_summary
----------------------------------------------------------------------

Notebook: 02_data_cleaning.ipynb | Cell: 11 | Matches: ['official_split']
print("=== CATEGORICAL VALUE CHECK ===")

print("\nDiagnoses:")
print(patients_df["diagnosis"].value_counts())

print("\nSex:")
print(patients_df["sex"].value_counts(dropna=False))

print("\nChest locations:")
print(recordings_df["chest_location"].value_counts())

print("\nAcquisition modes:")
print(recordings_df["acquisition_mode"].value_counts())

print("\nEquipment:")
print(recordings_df["equipment"].value_counts())

print("\nOfficial split:")
print(recordings_df["official_split"].value_counts())
----------------------------------------------------------------------

Notebook: 03_eda.ipynb | Cell: 35 | Matches: ['official_split']
split_disease_counts = pd.crosstab(
    recordings_disease_df["diagnosis"],
    recordings_disease_df["official_split"]
)

print("=== DISEASE × OFFICIAL SPLIT ===")

display(split_disease_counts)
----------------------------------------------------------------------

Notebook: 03_eda.ipynb | Cell: 36 | Matches: ['official_split']
split_disease_percent = (
    pd.crosstab(
        recordings_disease_df["diagnosis"],
        recordings_disease_df["official_split"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

print("=== DISEASE × OFFICIAL SPLIT (%) ===")

display(split_disease_percent)
----------------------------------------------------------------------

Notebook: 03_eda.ipynb | Cell: 40 | Matches: ['official_split']
# ============================================
# FINAL EDA SUMMARY TABLES
# ============================================

eda_summary = {
    "patients": len(patients_df),
    "recordings": len(recordings_df),
    "respiratory_cycles": len(cycles_df),

    "disease_classes": patients_df["diagnosis"].nunique(),
    "sound_classes": cycles_df["sound_label"].nunique(),

    "children_under_18": (
        patients_df["age"] < 18
    ).sum(),

    "adults_18_or_older": (
        patients_df["age"] >= 18
    ).sum(),

    "unknown_age": (
        patients_df["age"].isna()
    ).sum(),

    "train_recordings": (
        recordings_df["official_split"] == "train"
    ).sum(),

    "test_recordings": (
        recordings_df["official_split"] == "test"
    ).sum(),

    "sample_rates": (
        audio_info_df["sample_rate"].nunique()
    ),

    "chest_locations": (
        recordings_df["chest_location"].nunique()
    ),

    "equipment_types": (
        recordings_df["equipment"].nunique()
    )
}

print("=== FINAL EDA SUMMARY ===")

display(
    pd.DataFrame(
        [eda_summary]
    ).T.rename(columns={0: "value"})
)
----------------------------------------------------------------------

Notebook: 07_feature_selection.ipynb | Cell: 7 | Matches: ['official_split']
print("Official split distribution:")

display(
    recordings_df["official_split"]
    .value_counts()
)
----------------------------------------------------------------------

Notebook: 07_feature_selection.ipynb | Cell: 8 | Matches: ['official_split']
# ============================================================
# Attach Official Train/Test Split to Cycle Features
# ============================================================

split_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "official_split"
]

features_with_split = features_df.merge(
    recordings_df[split_columns],
    on=[
        "patient_id",
        "recording_id",
        "chest_location"
    ],
    how="left",
    validate="many_to_one"
)

print("Features with split shape:", features_with_split.shape)
display(
    features_with_split[
        [
            "patient_id",
            "recording_id",
            "chest_location",
            "official_split"
        ]
    ].head()
)
----------------------------------------------------------------------

Notebook: 07_feature_selection.ipynb | Cell: 9 | Matches: ['official_split']
print(
    "Missing official split values:",
    features_with_split["official_split"].isna().sum()
)
----------------------------------------------------------------------

Notebook: 07_feature_selection.ipynb | Cell: 10 | Matches: ['official_split']
# ============================================================
# Prepare Training Data for Feature Selection
# ============================================================

train_df = features_with_split[
    features_with_split["official_split"] == "train"
].copy()

test_df = features_with_split[
    features_with_split["official_split"] == "test"
].copy()

X_train = train_df[feature_columns].copy()

label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(
    train_df["diagnosis"]
)

print("Training cycles:", len(train_df))
print("Testing cycles:", len(test_df))
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
----------------------------------------------------------------------

Notebook: 08_pca_and_clustering.ipynb | Cell: 6 | Matches: ['official_split']
split_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "official_split"
]

features_with_split = features_df.merge(
    recordings_df[split_columns],
    on=[
        "patient_id",
        "recording_id",
        "chest_location"
    ],
    how="left",
    validate="many_to_one"
)

print(
    "Features with split shape:",
    features_with_split.shape
)

print(
    "Missing split values:",
    features_with_split[
        "official_split"
    ].isna().sum()
)
----------------------------------------------------------------------

Notebook: 08_pca_and_clustering.ipynb | Cell: 7 | Matches: ['official_split']
train_df = features_with_split[
    features_with_split["official_split"] == "train"
].copy()

test_df = features_with_split[
    features_with_split["official_split"] == "test"
].copy()

print("Training cycles:", len(train_df))
print("Testing cycles:", len(test_df))
----------------------------------------------------------------------

Notebook: 09_classical_ml.ipynb | Cell: 4 | Matches: ['official_split']
features_with_split = features_df.merge(
    recordings_df[
        [
            "patient_id",
            "recording_id",
            "chest_location",
            "official_split"
        ]
    ],
    on=[
        "patient_id",
        "recording_id",
        "chest_location"
    ],
    how="left",
    validate="many_to_one"
)

print("Merged dataset shape:", features_with_split.shape)

print(
    "Missing official split values:",
    features_with_split["official_split"].isna().sum()
)

print("\nOfficial split counts:")
print(features_with_split["official_split"].value_counts())
----------------------------------------------------------------------

Notebook: 09_classical_ml.ipynb | Cell: 5 | Matches: ['official_split']
train_df = features_with_split[
    features_with_split["official_split"] == "train"
].copy()

test_df = features_with_split[
    features_with_split["official_split"] == "test"
].copy()

print("Training cycles:", len(train_df))
print("Testing cycles :", len(test_df))

print("\nTraining disease distribution:")
print(train_df["diagnosis"].value_counts())

print("\nTesting disease distribution:")
print(test_df["diagnosis"].value_counts())
----------------------------------------------------------------------

Notebook: 09_classical_ml.ipynb | Cell: 14 | Matches: ['official_split']

from pathlib import Path
import json
import joblib
import sklearn
import pandas as pd

# Resolve the project root using the existing notebook variable.
project_root = Path(PROJECT_ROOT)
save_dir = project_root / "models" / "traditional_ml"
save_dir.mkdir(parents=True, exist_ok=True)

# Save the fitted estimators.
models_to_save = {
    "logistic_regression": logistic_model,
    "svm": svm_model,
    "random_forest": rf_model,
}

for model_name, model in models_to_save.items():
    output_path = save_dir / f"{model_name}.joblib"
    joblib.dump(model, output_path)
    print(f"Saved {model_name}: {output_path}")

# Save the shared preprocessing objects.
joblib.dump(scaler, save_dir / "scaler.joblib")
joblib.dump(label_encoder, save_dir / "label_encoder.joblib")

# Save feature order and metadata.
metadata = {
    "project": "Respiratory Disease Classification",
    "source_notebook": "notebooks/09_classical_ml.ipynb",
    "training_rows": int(len(train_df)),
    "test_rows": int(len(test_df)),
    "feature_count": int(len(selected_feature_names)),
    "selected_feature_names": list(selected_feature_names),
    "class_names": [str(c) for c in label_encoder.classes_],
    "scaler_used": {
        "logistic_regression": True,
        "svm": True,
        "random_forest": False,
    },
    "training_split": "Existing official_split; unchanged",
    "sklearn_version": sklearn.__version__,
    "models": {
        "logistic_regression": {
            "file": "logistic_regression.joblib",
            "class": type(logistic_model).__name__,
            "parameters": logistic_model.get_params(),
        },
        "svm": {
            "file": "svm.joblib",
            "class": type(svm_model).__name__,
            "parameters": svm_model.get_params(),
        },
        "random_fo
----------------------------------------------------------------------

Notebook: 10_deep_learning_data_preparation.ipynb | Cell: 4 | Matches: ['official_split']
features_with_split = processed_cycles_df.merge(
    recordings_df[
        [
            "patient_id",
            "recording_id",
            "chest_location",
            "official_split"
        ]
    ],
    on=[
        "patient_id",
        "recording_id",
        "chest_location"
    ],
    how="left",
    validate="many_to_one"
)

print("Merged dataset shape:", features_with_split.shape)

print("\nMissing official split values:")
print(
    features_with_split["official_split"].isna().sum()
)
----------------------------------------------------------------------

Notebook: 10_deep_learning_data_preparation.ipynb | Cell: 5 | Matches: ['official_split']
print("Official split distribution:")
print(
    features_with_split["official_split"]
    .value_counts()
)

print("\nSplit percentages:")
print(
    features_with_split["official_split"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)
----------------------------------------------------------------------

Notebook: 10_deep_learning_data_preparation.ipynb | Cell: 6 | Matches: ['official_split']
train_dl_df = features_with_split[
    features_with_split["official_split"] == "train"
].copy()

test_dl_df = features_with_split[
    features_with_split["official_split"] == "test"
].copy()


In [10]:
from pathlib import Path
import pandas as pd

metadata_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "recordings.csv"
)

if not metadata_path.exists():
    raise FileNotFoundError(
        f"Metadata file not found: {metadata_path}"
    )

recordings = pd.read_csv(metadata_path)

print("Metadata columns:", recordings.columns.tolist())

required = {"patient_id", "recording_id", "official_split"}
missing = required - set(recordings.columns)

if missing:
    raise ValueError(f"Missing required columns: {sorted(missing)}")

focus = recordings[
    recordings["patient_id"].astype(str).isin(["156", "218"])
].copy()

print("\n=== ORIGINAL RECORDING METADATA ===")

display(
    focus.sort_values(
        ["patient_id", "recording_id", "official_split"]
    )
)

print("\n=== SPLIT ASSIGNMENTS PER PATIENT ===")

display(
    focus.groupby("patient_id").agg(
        recordings=("recording_id", "nunique"),
        split_count=("official_split", "nunique"),
        splits=(
            "official_split",
            lambda x: ", ".join(sorted(x.dropna().astype(str).unique()))
        ),
    )
)

print("\n=== PATIENT-RECORDING KEYS WITH MULTIPLE SPLITS ===")

key_summary = (
    recordings.groupby(["patient_id", "recording_id"])
    .agg(
        split_count=("official_split", "nunique"),
        splits=(
            "official_split",
            lambda x: ", ".join(sorted(x.dropna().astype(str).unique()))
        ),
    )
    .reset_index()
)

display(
    key_summary[
        (key_summary["patient_id"].astype(str).isin(["156", "218"]))
        & (key_summary["split_count"] > 1)
    ]
)

print("\nAudit complete. No files were modified.")

Metadata columns: ['patient_id', 'recording_id', 'chest_location', 'acquisition_mode', 'equipment', 'wav_path', 'official_split']

=== ORIGINAL RECORDING METADATA ===

,patient_id,recording_id,chest_location,acquisition_mode,equipment,wav_path,official_split
362,156,2b3,Al,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
365,156,2b3,Lr,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
366,156,2b3,Pl,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
363,156,2b3,Ar,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
364,156,2b3,Ll,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
367,156,2b3,Pr,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
369,156,5b3,Ar,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
370,156,5b3,Ll,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
372,156,5b3,Pl,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
368,156,5b3,Al,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
371,156,5b3,Lr,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
373,156,5b3,Pr,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
374,156,8b3,Al,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
377,156,8b3,Lr,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
375,156,8b3,Ar,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
376,156,8b3,Ll,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
378,156,8b3,Pl,mc,AKGC417L,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
878,218,1b1,Al,sc,Meditron,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
881,218,1b1,Pl,sc,Meditron,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
882,218,1b1,Pr,sc,Meditron,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
879,218,1b1,Ar,sc,Meditron,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
880,218,1b1,Lr,sc,Meditron,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
884,218,1p1,Pl,sc,Litt3200,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,test
883,218,1p1,Ar,sc,Litt3200,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train
885,218,1p1,Pr,sc,Litt3200,/Users/vs/Sem 5/Respiratory-Disease-Classifica...,train

=== SPLIT ASSIGNMENTS PER PATIENT ===

            recordings  split_count       splits
patient_id
156                  3            2  test, train
218                  2            2  test, train

=== PATIENT-RECORDING KEYS WITH MULTIPLE SPLITS ===

     patient_id recording_id  split_count       splits
108         156          2b3            2  test, train
109         156          5b3            2  test, train
110         156          8b3            2  test, train
240         218          1b1            2  test, train
241         218          1p1            2  test, train

Audit complete. No files were modified.

In [11]:

import pandas as pd

# Work on copies. Do not modify or overwrite the original manifests.
train_patients_official = set(
    train_manifest["patient_id"].astype(str)
)
test_patients_official = set(
    test_manifest["patient_id"].astype(str)
)

overlap_patients = (
    train_patients_official & test_patients_official
)

# Strict development cohort:
# only patients appearing in official training and never in official test.
development_manifest = train_manifest[
    ~train_manifest["patient_id"].astype(str).isin(
        test_patients_official
    )
].copy()

development_patients = set(
    development_manifest["patient_id"].astype(str)
)

print("=== PATIENT-DISJOINT DEVELOPMENT COHORT ===")
print("Original training-manifest rows:", len(train_manifest))
print("Original official test rows:", len(test_manifest))
print("Patients in official training:", len(train_patients_official))
print("Patients in official test:", len(test_patients_official))
print("Patients shared by official partitions:", len(overlap_patients))
print("Development rows after exclusion:", len(development_manifest))
print("Development patients:", len(development_patients))
print(
    "Development patients overlapping official test:",
    len(development_patients & test_patients_official)
)

print("\nDevelopment class distribution:")
print(
    development_manifest["diagnosis"]
    .value_counts()
    .sort_index()
)

assert development_patients.isdisjoint(test_patients_official)
assert development_manifest["diagnosis"].notna().all()

print("\nPASS: development patients are disjoint from official test patients.")
print("No files were modified.")

=== PATIENT-DISJOINT DEVELOPMENT COHORT ===
Original training-manifest rows: 4142
Original official test rows: 2756
Patients in official training: 79
Patients in official test: 49
Patients shared by official partitions: 2
Development rows after exclusion: 4025
Development patients: 77
Development patients overlapping official test: 0

Development class distribution:
diagnosis
Asthma               6
Bronchiectasis      90
Bronchiolitis       74
COPD              3220
Healthy            147
LRTI                32
Pneumonia          285
URTI               171
Name: count, dtype: int64

PASS: development patients are disjoint from official test patients.
No files were modified.

In [12]:

# Count distinct patients and respiratory-cycle rows for each diagnosis.
class_support = (
    development_manifest
    .groupby("diagnosis")
    .agg(
        cycle_rows=("patient_id", "size"),
        unique_patients=("patient_id", "nunique"),
    )
    .sort_values("unique_patients")
)

print("=== DEVELOPMENT SUPPORT BY CLASS ===")
display(class_support)

print("\n=== PATIENT-LEVEL DIAGNOSIS CONSISTENCY ===")
patient_diagnoses = (
    development_manifest
    .groupby("patient_id")["diagnosis"]
    .nunique()
)

print("Development patients:", patient_diagnoses.size)
print(
    "Patients with multiple diagnoses:",
    int((patient_diagnoses > 1).sum())
)

print("\n=== MINIMUM CLASS SUPPORT ===")
print("Fewest distinct patients in a class:",
      int(class_support["unique_patients"].min()))
print("Classes with fewer than 5 patients:")
display(class_support[class_support["unique_patients"] < 5])

=== DEVELOPMENT SUPPORT BY CLASS ===

                cycle_rows  unique_patients
diagnosis
Asthma                   6                1
LRTI                    32                2
Bronchiolitis           74                3
Bronchiectasis          90                6
Pneumonia              285                6
URTI                   171               10
Healthy                147               12
COPD                  3220               37

=== PATIENT-LEVEL DIAGNOSIS CONSISTENCY ===
Development patients: 77
Patients with multiple diagnoses: 0

=== MINIMUM CLASS SUPPORT ===
Fewest distinct patients in a class: 1
Classes with fewer than 5 patients:

               cycle_rows  unique_patients
diagnosis
Asthma                  6                1
LRTI                   32                2
Bronchiolitis          74                3

In [13]:

# Summarize which development patients contribute to each diagnosis.
patient_class_table = (
    development_manifest[
        ["patient_id", "diagnosis"]
    ]
    .drop_duplicates()
    .sort_values(["diagnosis", "patient_id"])
)

print("=== PATIENTS REPRESENTING EACH DIAGNOSIS ===")

for diagnosis, group in patient_class_table.groupby("diagnosis"):
    patients = sorted(group["patient_id"].astype(str).unique())
    print(f"{diagnosis}: {len(patients)} patient(s) -> {patients}")

print("\n=== TOTAL UNIQUE DEVELOPMENT PATIENTS ===")
print(patient_class_table["patient_id"].nunique())

print("\nNo files were modified.")

=== PATIENTS REPRESENTING EACH DIAGNOSIS ===
Asthma: 1 patient(s) -> ['103']
Bronchiectasis: 6 patient(s) -> ['111', '116', '168', '196', '201', '215']
Bronchiolitis: 3 patient(s) -> ['161', '167', '206']
COPD: 37 patient(s) -> ['106', '107', '110', '112', '114', '117', '120', '128', '130', '132', '134', '138', '141', '142', '154', '155', '157', '158', '162', '163', '166', '172', '180', '181', '186', '189', '192', '193', '199', '200', '203', '204', '212', '213', '220', '221', '222']
Healthy: 12 patient(s) -> ['121', '125', '127', '152', '153', '159', '179', '183', '184', '208', '209', '217']
LRTI: 2 patient(s) -> ['108', '115']
Pneumonia: 6 patient(s) -> ['122', '135', '140', '191', '219', '226']
URTI: 10 patient(s) -> ['105', '129', '131', '137', '148', '164', '188', '190', '197', '210']

=== TOTAL UNIQUE DEVELOPMENT PATIENTS ===
77

No files were modified.

In [14]:

# Inspect all available patients per diagnosis in the full feature table.
# This is an audit only; no training or file modification occurs.

full_patient_class = (
    features_df[["patient_id", "diagnosis"]]
    .dropna()
    .drop_duplicates()
)

full_support = (
    full_patient_class
    .groupby("diagnosis")
    .agg(unique_patients=("patient_id", "nunique"))
    .sort_values("unique_patients")
)

print("=== FULL FEATURE TABLE: PATIENT SUPPORT BY DIAGNOSIS ===")
display(full_support)

print("\n=== DEVELOPMENT VS FULL DATASET ===")
development_support = (
    development_manifest[["patient_id", "diagnosis"]]
    .drop_duplicates()
    .groupby("diagnosis")
    .agg(development_patients=("patient_id", "nunique"))
)

comparison = full_support.join(development_support, how="left")
comparison["development_patients"] = (
    comparison["development_patients"].fillna(0).astype(int)
)
comparison["patients_outside_development"] = (
    comparison["unique_patients"]
    - comparison["development_patients"]
)

display(comparison)

print("\nNo files were modified.")

=== FULL FEATURE TABLE: PATIENT SUPPORT BY DIAGNOSIS ===

                unique_patients
diagnosis
Asthma                        1
LRTI                          2
Bronchiolitis                 6
Pneumonia                     6
Bronchiectasis                7
URTI                         14
Healthy                      26
COPD                         64

=== DEVELOPMENT VS FULL DATASET ===

,unique_patients,development_patients,patients_outside_development
diagnosis,,,
Asthma,1,1,0
LRTI,2,2,0
Bronchiolitis,6,3,3
Pneumonia,6,6,0
Bronchiectasis,7,6,1
URTI,14,10,4
Healthy,26,12,14
COPD,64,37,27

No files were modified.

In [15]:

# Inspect all available patients per diagnosis in the full feature table.
# This is an audit only; no training or file modification occurs.

full_patient_class = (
    features_df[["patient_id", "diagnosis"]]
    .dropna()
    .drop_duplicates()
)

full_support = (
    full_patient_class
    .groupby("diagnosis")
    .agg(unique_patients=("patient_id", "nunique"))
    .sort_values("unique_patients")
)

print("=== FULL FEATURE TABLE: PATIENT SUPPORT BY DIAGNOSIS ===")
display(full_support)

print("\n=== DEVELOPMENT VS FULL DATASET ===")
development_support = (
    development_manifest[["patient_id", "diagnosis"]]
    .drop_duplicates()
    .groupby("diagnosis")
    .agg(development_patients=("patient_id", "nunique"))
)

comparison = full_support.join(development_support, how="left")
comparison["development_patients"] = (
    comparison["development_patients"].fillna(0).astype(int)
)
comparison["patients_outside_development"] = (
    comparison["unique_patients"]
    - comparison["development_patients"]
)

display(comparison)

print("\nNo files were modified.")

=== FULL FEATURE TABLE: PATIENT SUPPORT BY DIAGNOSIS ===

                unique_patients
diagnosis
Asthma                        1
LRTI                          2
Bronchiolitis                 6
Pneumonia                     6
Bronchiectasis                7
URTI                         14
Healthy                      26
COPD                         64

=== DEVELOPMENT VS FULL DATASET ===

,unique_patients,development_patients,patients_outside_development
diagnosis,,,
Asthma,1,1,0
LRTI,2,2,0
Bronchiolitis,6,3,3
Pneumonia,6,6,0
Bronchiectasis,7,6,1
URTI,14,10,4
Healthy,26,12,14
COPD,64,37,27

No files were modified.

In [16]:

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

# Merge the development manifest with the existing feature table.
# Use the manifest to establish which cycles belong to development.
join_keys = ["patient_id", "recording_id", "chest_location", "diagnosis"]

development_keys = development_manifest[join_keys].drop_duplicates()

development_features = features_df.merge(
    development_keys,
    on=join_keys,
    how="inner",
    validate="many_to_one"
)

print("Development feature rows:", len(development_features))
print("Development patients:", development_features["patient_id"].nunique())

# Try 3 folds first because the rarest diagnoses have very few patients.
for n_splits in [3, 4, 5]:
    print(f"\n=== {n_splits}-FOLD STRATIFIED GROUP CHECK ===")

    splitter = StratifiedGroupKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=42
    )

    y = development_features["diagnosis"].astype(str)
    groups = development_features["patient_id"].astype(str)

    fold_rows = []

    try:
        for fold, (train_idx, val_idx) in enumerate(
            splitter.split(development_features, y, groups),
            start=1
        ):
            train_df = development_features.iloc[train_idx]
            val_df = development_features.iloc[val_idx]

            train_classes = set(train_df["diagnosis"])
            val_classes = set(val_df["diagnosis"])

            fold_rows.append({
                "fold": fold,
                "train_patients": train_df["patient_id"].nunique(),
                "validation_patients": val_df["patient_id"].nunique(),
                "train_classes": len(train_classes),
                "validation_classes": len(val_classes),
                "missing_validation_classes": ", ".join(
                    sorted(set(y.unique()) - val_classes)
                ) or "None",
                "patient_overlap": len(
                    set(train_df["patient_id"].astype(str))
                    & set(val_df["patient_id"].astype(str))
                )
            })

        display(pd.DataFrame(fold_rows))

    except ValueError as exc:
        print("Fold generation failed:", exc)

print("\nNo models were trained and no files were modified.")

Development feature rows: 4025
Development patients: 77

=== 3-FOLD STRATIFIED GROUP CHECK ===

,fold,train_patients,validation_patients,train_classes,validation_classes,missing_validation_classes,patient_overlap
0,1,55,22,8,6,"Asthma, LRTI",0
1,2,50,27,8,7,Asthma,0
2,3,49,28,7,8,None,0

=== 4-FOLD STRATIFIED GROUP CHECK ===

,fold,train_patients,validation_patients,train_classes,validation_classes,missing_validation_classes,patient_overlap
0,1,59,18,8,7,Asthma,0
1,2,57,20,8,7,Asthma,0
2,3,56,21,8,6,"Asthma, LRTI",0
3,4,59,18,7,6,"Bronchiolitis, LRTI",0

=== 5-FOLD STRATIFIED GROUP CHECK ===

,fold,train_patients,validation_patients,train_classes,validation_classes,missing_validation_classes,patient_overlap
0,1,63,14,7,7,LRTI,0
1,2,59,18,8,7,Asthma,0
2,3,62,15,8,7,Asthma,0
3,4,62,15,8,5,"Asthma, Bronchiolitis, LRTI",0
4,5,62,15,8,5,"Asthma, Bronchiolitis, LRTI",0

No models were trained and no files were modified.

In [17]:

# Validate the exact development features and labels before model tuning.
# This cell does not train a model or save files.

selected_features = pd.read_csv(
    SELECTED_FEATURES_PATH
)["feature"].tolist()

required_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "diagnosis",
]

missing_columns = [
    col for col in required_columns + selected_features
    if col not in development_features.columns
]

print("Selected features:", len(selected_features))
print("Missing required columns:", missing_columns)

X_dev = development_features[selected_features].copy()
y_dev = development_features["diagnosis"].astype(str).copy()
groups_dev = development_features["patient_id"].astype(str).copy()

# Convert selected features to numeric explicitly.
X_dev = X_dev.apply(pd.to_numeric, errors="coerce")

print("\n=== INPUT QUALITY CHECK ===")
print("Feature matrix shape:", X_dev.shape)
print("Label count:", len(y_dev))
print("Patient-group count:", groups_dev.nunique())
print("Missing feature values:", int(X_dev.isna().sum().sum()))
print("Infinite feature values:", int(np.isinf(X_dev.to_numpy()).sum()))
print("Duplicate feature column names:", X_dev.columns.duplicated().sum())
print("Duplicate manifest keys:", development_features.duplicated(
    ["patient_id", "recording_id", "chest_location", "diagnosis"]
).sum())

print("\n=== LABEL COUNTS ===")
display(y_dev.value_counts().sort_index())

assert not missing_columns, f"Missing columns: {missing_columns}"
assert len(X_dev) == len(y_dev) == len(groups_dev)
assert X_dev.columns.is_unique
assert X_dev.notna().all().all(), "Missing or non-numeric feature values found."
assert np.isfinite(X_dev.to_numpy()).all(), "Infinite feature values found."

print("\nPASS: feature inputs are ready for the next validation step.")
print("No model was trained and no files were modified.")

Selected features: 33
Missing required columns: []

=== INPUT QUALITY CHECK ===
Feature matrix shape: (4025, 33)
Label count: 4025
Patient-group count: 77
Missing feature values: 0
Infinite feature values: 0
Duplicate feature column names: 0
Duplicate manifest keys: 3499

=== LABEL COUNTS ===

diagnosis
Asthma               6
Bronchiectasis      90
Bronchiolitis       74
COPD              3220
Healthy            147
LRTI                32
Pneumonia          285
URTI               171
Name: count, dtype: int64

PASS: feature inputs are ready for the next validation step.
No model was trained and no files were modified.

In [18]:

# Determine whether duplicate keys are expected multiple cycles or
# whether the manifest-to-feature merge multiplied rows.

key_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "diagnosis",
]

print("=== ROW COUNTS ===")
print("Full feature table:", len(features_df))
print("Development manifest:", len(development_manifest))
print("Merged development features:", len(development_features))

print("\n=== KEY UNIQUENESS ===")
print(
    "Unique keys in development manifest:",
    development_manifest[key_columns].drop_duplicates().shape[0]
)
print(
    "Unique keys in merged development features:",
    development_features[key_columns].drop_duplicates().shape[0]
)

print("\n=== FEATURE ROWS PER KEY ===")
feature_key_counts = (
    development_features.groupby(key_columns, dropna=False)
    .size()
    .rename("rows_per_key")
    .reset_index()
)

print("Keys with multiple feature rows:", int(
    (feature_key_counts["rows_per_key"] > 1).sum()
))
print("Maximum rows for one key:", int(feature_key_counts["rows_per_key"].max()))

print("\nExamples of keys with multiple rows:")
display(
    feature_key_counts[
        feature_key_counts["rows_per_key"] > 1
    ].head(10)
)

print("\n=== ORIGINAL FEATURE TABLE DUPLICATE KEY COUNTS ===")
original_dev = features_df.merge(
    development_manifest[key_columns].drop_duplicates(),
    on=key_columns,
    how="inner",
    validate="many_to_one"
)

print("Original feature rows matching development keys:", len(original_dev))
print(
    "Duplicate full rows in matched feature data:",
    int(original_dev.duplicated().sum())
)

print("\nNo files were modified.")

=== ROW COUNTS ===
Full feature table: 6898
Development manifest: 4025
Merged development features: 4025

=== KEY UNIQUENESS ===
Unique keys in development manifest: 526
Unique keys in merged development features: 526

=== FEATURE ROWS PER KEY ===
Keys with multiple feature rows: 526
Maximum rows for one key: 33

Examples of keys with multiple rows:

   patient_id recording_id chest_location diagnosis  rows_per_key
0         103          2b2             Ar    Asthma             6
1         105          1b1             Tc      URTI             8
2         106          2b1             Pl      COPD             9
3         106          2b1             Pr      COPD             9
4         107          2b3             Al      COPD             8
5         107          2b3             Ar      COPD             8
6         107          2b3             Ll      COPD             8
7         107          2b3             Lr      COPD             8
8         107          2b3             Pl      COPD             8
9         107          2b3             Pr      COPD             8

=== ORIGINAL FEATURE TABLE DUPLICATE KEY COUNTS ===
Original feature rows matching development keys: 4025
Duplicate full rows in matched feature data: 0

No files were modified.

In [19]:

from sklearn.base import clone
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    classification_report,
)

# Reproducible baseline; no hyperparameter search yet.
baseline_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        class_weight="balanced",
        C=1.0,
        gamma="scale",
        probability=False,
        random_state=42,
    )),
])

cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

baseline_results = []
baseline_oof = pd.DataFrame({
    "patient_id": groups_dev.to_numpy(),
    "y_true": y_dev.to_numpy(),
    "y_pred": [None] * len(y_dev),
})

for fold, (train_idx, val_idx) in enumerate(
    cv.split(X_dev, y_dev, groups_dev),
    start=1,
):
    model = clone(baseline_model)

    X_train, X_val = X_dev.iloc[train_idx], X_dev.iloc[val_idx]
    y_train, y_val = y_dev.iloc[train_idx], y_dev.iloc[val_idx]

    model.fit(X_train, y_train)
    predictions = model.predict(X_val)

    baseline_oof.loc[val_idx, "y_pred"] = predictions

    baseline_results.append({
        "fold": fold,
        "train_patients": groups_dev.iloc[train_idx].nunique(),
        "validation_patients": groups_dev.iloc[val_idx].nunique(),
        "accuracy": accuracy_score(y_val, predictions),
        "balanced_accuracy": balanced_accuracy_score(y_val, predictions),
        "macro_f1": f1_score(
            y_val, predictions, average="macro", zero_division=0
        ),
        "weighted_f1": f1_score(
            y_val, predictions, average="weighted", zero_division=0
        ),
    })

baseline_results_df = pd.DataFrame(baseline_results)

print("=== PATIENT-GROUPED RBF-SVM BASELINE ===")
display(baseline_results_df.round(4))

print("\n=== FOLD MEAN AND STANDARD DEVIATION ===")
display(
    baseline_results_df[
        ["accuracy", "balanced_accuracy", "macro_f1", "weighted_f1"]
    ].agg(["mean", "std"]).round(4)
)

print("\n=== OUT-OF-FOLD CLASSIFICATION REPORT ===")
print(classification_report(
    baseline_oof["y_true"],
    baseline_oof["y_pred"],
    labels=sorted(y_dev.unique()),
    zero_division=0,
))

print("No model files were saved or overwritten.")

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

=== PATIENT-GROUPED RBF-SVM BASELINE ===

,fold,train_patients,validation_patients,accuracy,balanced_accuracy,macro_f1,weighted_f1
0,1,55,22,0.6791,0.3908,0.2916,0.7286
1,2,50,27,0.7585,0.3401,0.2614,0.7672
2,3,49,28,0.6998,0.2319,0.2059,0.7267

=== FOLD MEAN AND STANDARD DEVIATION ===

      accuracy  balanced_accuracy  macro_f1  weighted_f1
mean    0.7125             0.3209    0.2530       0.7408
std     0.0412             0.0812    0.0435       0.0229

=== OUT-OF-FOLD CLASSIFICATION REPORT ===
                precision    recall  f1-score   support

        Asthma       0.00      0.00      0.00         6
Bronchiectasis       0.22      0.28      0.25        90
 Bronchiolitis       0.00      0.00      0.00        74
          COPD       0.93      0.81      0.87      3220
       Healthy       0.30      0.57      0.40       147
          LRTI       0.00      0.00      0.00        32
     Pneumonia       0.22      0.38      0.28       285
          URTI       0.19      0.20      0.20       171

      accuracy                           0.71      4025
     macro avg       0.23      0.28      0.25      4025
  weighted avg       0.78      0.71      0.74      4025

No model files were saved or overwritten.

In [20]:

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    f1_score,
    balanced_accuracy_score,
)
import pandas as pd
import numpy as np

# Explicitly use all eight known classes for consistent reporting.
class_order = [
    "Asthma",
    "Bronchiectasis",
    "Bronchiolitis",
    "COPD",
    "Healthy",
    "LRTI",
    "Pneumonia",
    "URTI",
]

y_true_oof = baseline_oof["y_true"].astype(str)
y_pred_oof = baseline_oof["y_pred"].astype(str)

print("=== OVERALL OUT-OF-FOLD METRICS ===")
print("Rows:", len(baseline_oof))
print("Accuracy:", round((y_true_oof == y_pred_oof).mean(), 4))
print(
    "Balanced accuracy:",
    round(balanced_accuracy_score(y_true_oof, y_pred_oof), 4)
)
print(
    "Macro-F1:",
    round(f1_score(
        y_true_oof, y_pred_oof,
        labels=class_order,
        average="macro",
        zero_division=0,
    ), 4)
)

print("\n=== CLASSIFICATION REPORT ===")
report = classification_report(
    y_true_oof,
    y_pred_oof,
    labels=class_order,
    output_dict=True,
    zero_division=0,
)
display(pd.DataFrame(report).T.round(4))

print("\n=== CONFUSION MATRIX ===")
cm = confusion_matrix(
    y_true_oof,
    y_pred_oof,
    labels=class_order,
)
display(pd.DataFrame(
    cm,
    index=[f"True: {c}" for c in class_order],
    columns=[f"Pred: {c}" for c in class_order],
))

print("\n=== PREDICTED CLASS COUNTS ===")
display(y_pred_oof.value_counts().reindex(class_order, fill_value=0))

print("\nNo models were trained and no files were modified.")

=== OVERALL OUT-OF-FOLD METRICS ===
Rows: 4025
Accuracy: 0.7125
Balanced accuracy: 0.2796
Macro-F1: 0.2482

=== CLASSIFICATION REPORT ===

                precision  recall  f1-score    support
Asthma             0.0000  0.0000    0.0000     6.0000
Bronchiectasis     0.2212  0.2778    0.2463    90.0000
Bronchiolitis      0.0000  0.0000    0.0000    74.0000
COPD               0.9310  0.8130    0.8680  3220.0000
Healthy            0.3022  0.5714    0.3953   147.0000
LRTI               0.0000  0.0000    0.0000    32.0000
Pneumonia          0.2234  0.3754    0.2801   285.0000
URTI               0.1932  0.1988    0.1960   171.0000
accuracy           0.7125  0.7125    0.7125     0.7125
macro avg          0.2339  0.2796    0.2482  4025.0000
weighted avg       0.7848  0.7125    0.7425  4025.0000

=== CONFUSION MATRIX ===

,Pred: Asthma,Pred: Bronchiectasis,Pred: Bronchiolitis,Pred: COPD,Pred: Healthy,Pred: LRTI,Pred: Pneumonia,Pred: URTI
True: Asthma,0,0,0,0,3,0,0,3
True: Bronchiectasis,0,25,2,61,0,0,0,2
True: Bronchiolitis,0,8,0,8,10,0,7,41
True: COPD,0,79,55,2618,106,9,327,26
True: Healthy,0,0,5,7,84,6,15,30
True: LRTI,0,0,1,2,7,0,9,13
True: Pneumonia,0,0,34,78,32,7,107,27
True: URTI,1,1,29,38,36,18,14,34

=== PREDICTED CLASS COUNTS ===

y_pred
Asthma               1
Bronchiectasis     113
Bronchiolitis      126
COPD              2812
Healthy            278
LRTI                40
Pneumonia          479
URTI               176
Name: count, dtype: int64

No models were trained and no files were modified.

In [21]:

from sklearn.model_selection import StratifiedGroupKFold, ParameterGrid
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import f1_score, balanced_accuracy_score, accuracy_score
from sklearn.base import clone
import pandas as pd
import numpy as np

# Use the same three patient-grouped folds as the baseline.
cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

param_grid = {
    "svm__C": [0.1, 1, 10, 100],
    "svm__gamma": ["scale", 0.001, 0.01, 0.1],
    "svm__class_weight": ["balanced", None],
}

base_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        probability=False,
        random_state=42,
    )),
])

# Materialize folds once so every configuration uses identical partitions.
folds = list(cv.split(X_dev, y_dev, groups_dev))
search_results = []

for config_number, params in enumerate(ParameterGrid(param_grid), start=1):
    fold_scores = []

    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = clone(base_pipeline).set_params(**params)

        X_train = X_dev.iloc[train_idx]
        X_val = X_dev.iloc[val_idx]
        y_train = y_dev.iloc[train_idx]
        y_val = y_dev.iloc[val_idx]

        model.fit(X_train, y_train)
        predictions = model.predict(X_val)

        fold_scores.append({
            "macro_f1": f1_score(
                y_val, predictions,
                labels=sorted(y_dev.unique()),
                average="macro",
                zero_division=0,
            ),
            "balanced_accuracy": balanced_accuracy_score(
                y_val, predictions
            ),
            "accuracy": accuracy_score(y_val, predictions),
        })

    row = dict(params)
    for metric in ["macro_f1", "balanced_accuracy", "accuracy"]:
        values = [score[metric] for score in fold_scores]
        row[f"{metric}_mean"] = float(np.mean(values))
        row[f"{metric}_std"] = float(np.std(values, ddof=1))

    search_results.append(row)

search_results_df = (
    pd.DataFrame(search_results)
    .sort_values(
        ["macro_f1_mean", "balanced_accuracy_mean"],
        ascending=False,
    )
    .reset_index(drop=True)
)

print("Configurations evaluated:", len(search_results_df))
print("\n=== TOP 10 CONFIGURATIONS ===")
display(search_results_df.head(10).round(4))

print("\n=== BEST CONFIGURATION ===")
display(search_results_df.head(1).round(4))

print("\nNo files were saved or overwritten.")

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Configurations evaluated: 32

=== TOP 10 CONFIGURATIONS ===

,svm__C,svm__class_weight,svm__gamma,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,balanced,0.01,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275
1,10.0,balanced,scale,0.2423,0.0396,0.2914,0.0815,0.7555,0.0228
2,10.0,balanced,0.01,0.2419,0.0344,0.3140,0.0839,0.7244,0.0372
3,100.0,balanced,0.001,0.2417,0.0473,0.3378,0.1353,0.6782,0.0433
4,1.0,balanced,scale,0.2408,0.0304,0.3209,0.0812,0.7125,0.0412
5,1.0,balanced,0.01,0.2408,0.0333,0.3522,0.1057,0.6526,0.0508
6,100.0,balanced,scale,0.2318,0.0340,0.2691,0.0762,0.7674,0.0155
7,0.1,balanced,scale,0.2295,0.0232,0.3434,0.1137,0.6265,0.0775
8,100.0,NaN,0.01,0.2286,0.0265,0.2718,0.0726,0.7609,0.0283
9,10.0,balanced,0.001,0.2257,0.0345,0.3380,0.1152,0.6093,0.0705

=== BEST CONFIGURATION ===

,svm__C,svm__class_weight,svm__gamma,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,balanced,0.01,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275

No files were saved or overwritten.

In [1]:

from sklearn.model_selection import StratifiedGroupKFold, ParameterGrid
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import f1_score, balanced_accuracy_score, accuracy_score
from sklearn.base import clone
import pandas as pd
import numpy as np

# Use the same three patient-grouped folds as the baseline.
cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

param_grid = {
    "svm__C": [0.1, 1, 10, 100],
    "svm__gamma": ["scale", 0.001, 0.01, 0.1],
    "svm__class_weight": ["balanced", None],
}

base_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        probability=False,
        random_state=42,
    )),
])

# Materialize folds once so every configuration uses identical partitions.
folds = list(cv.split(X_dev, y_dev, groups_dev))
search_results = []

for config_number, params in enumerate(ParameterGrid(param_grid), start=1):
    fold_scores = []

    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = clone(base_pipeline).set_params(**params)

        X_train = X_dev.iloc[train_idx]
        X_val = X_dev.iloc[val_idx]
        y_train = y_dev.iloc[train_idx]
        y_val = y_dev.iloc[val_idx]

        model.fit(X_train, y_train)
        predictions = model.predict(X_val)

        fold_scores.append({
            "macro_f1": f1_score(
                y_val, predictions,
                labels=sorted(y_dev.unique()),
                average="macro",
                zero_division=0,
            ),
            "balanced_accuracy": balanced_accuracy_score(
                y_val, predictions
            ),
            "accuracy": accuracy_score(y_val, predictions),
        })

    row = dict(params)
    for metric in ["macro_f1", "balanced_accuracy", "accuracy"]:
        values = [score[metric] for score in fold_scores]
        row[f"{metric}_mean"] = float(np.mean(values))
        row[f"{metric}_std"] = float(np.std(values, ddof=1))

    search_results.append(row)

search_results_df = (
    pd.DataFrame(search_results)
    .sort_values(
        ["macro_f1_mean", "balanced_accuracy_mean"],
        ascending=False,
    )
    .reset_index(drop=True)
)

print("Configurations evaluated:", len(search_results_df))
print("\n=== TOP 10 CONFIGURATIONS ===")
display(search_results_df.head(10).round(4))

print("\n=== BEST CONFIGURATION ===")
display(search_results_df.head(1).round(4))

print("\nNo files were saved or overwritten.")

NameError: name 'X_dev' is not defined

In [4]:

from pathlib import Path
import pandas as pd
import numpy as np

# Recreate project paths from the notebook's expected folder structure.
PROJECT_ROOT = Path.cwd().parent

FEATURES_PATH = (
    PROJECT_ROOT / "data" / "processed" / "features"
    / "respiratory_cycle_features.csv"
)

TRAIN_MANIFEST_PATH = (
    PROJECT_ROOT / "data" / "processed" / "deep_learning"
    / "train_manifest.csv"
)

TEST_MANIFEST_PATH = (
    PROJECT_ROOT / "data" / "processed" / "deep_learning"
    / "test_manifest.csv"
)

SELECTED_FEATURES_PATH = (
    PROJECT_ROOT / "data" / "processed" / "classical_ml"
    / "classical_ml_selected_features.csv"
)

print("Project root:", PROJECT_ROOT)
print("Feature table exists:", FEATURES_PATH.exists())
print("Training manifest exists:", TRAIN_MANIFEST_PATH.exists())
print("Test manifest exists:", TEST_MANIFEST_PATH.exists())
print("Selected features file exists:", SELECTED_FEATURES_PATH.exists())

assert FEATURES_PATH.exists(), f"Missing file: {FEATURES_PATH}"
assert TRAIN_MANIFEST_PATH.exists(), f"Missing file: {TRAIN_MANIFEST_PATH}"
assert TEST_MANIFEST_PATH.exists(), f"Missing file: {TEST_MANIFEST_PATH}"
assert SELECTED_FEATURES_PATH.exists(), f"Missing file: {SELECTED_FEATURES_PATH}"

print("\nPASS: all required paths exist.")

Project root: /Users/vs/Sem 5/Respiratory-Disease-Classification
Feature table exists: True
Training manifest exists: True
Test manifest exists: True
Selected features file exists: True

PASS: all required paths exist.

In [5]:

# Reload the original project data.
features_df = pd.read_csv(FEATURES_PATH)
train_manifest = pd.read_csv(TRAIN_MANIFEST_PATH)
test_manifest = pd.read_csv(TEST_MANIFEST_PATH)

selected_features = pd.read_csv(
    SELECTED_FEATURES_PATH
)["feature"].tolist()

# Exclude every patient appearing in the official test manifest.
test_patients = set(test_manifest["patient_id"].astype(str))

development_manifest = train_manifest[
    ~train_manifest["patient_id"].astype(str).isin(test_patients)
].copy()

# Match feature rows to development manifest keys.
join_keys = [
    "patient_id",
    "recording_id",
    "chest_location",
    "diagnosis",
]

development_keys = development_manifest[join_keys].drop_duplicates()

development_features = features_df.merge(
    development_keys,
    on=join_keys,
    how="inner",
    validate="many_to_one",
)

# Rebuild the model inputs.
X_dev = development_features[selected_features].apply(
    pd.to_numeric, errors="coerce"
).copy()

y_dev = development_features["diagnosis"].astype(str).copy()
groups_dev = development_features["patient_id"].astype(str).copy()

print("Development feature matrix:", X_dev.shape)
print("Development labels:", len(y_dev))
print("Unique development patients:", groups_dev.nunique())
print("Selected features:", len(selected_features))
print("Missing feature values:", int(X_dev.isna().sum().sum()))
print("Infinite feature values:", int(np.isinf(X_dev.to_numpy()).sum()))
print(
    "Patient overlap with official test:",
    len(set(groups_dev) & test_patients)
)

assert len(X_dev) == len(y_dev) == len(groups_dev)
assert X_dev.columns.is_unique
assert X_dev.notna().all().all()
assert np.isfinite(X_dev.to_numpy()).all()
assert set(groups_dev).isdisjoint(test_patients)

print("\nPASS: development inputs restored and validated.")
print("No model was trained and no files were modified.")

Development feature matrix: (4025, 33)
Development labels: 4025
Unique development patients: 77
Selected features: 33
Missing feature values: 0
Infinite feature values: 0
Patient overlap with official test: 0

PASS: development inputs restored and validated.
No model was trained and no files were modified.

In [6]:

from sklearn.model_selection import StratifiedGroupKFold, ParameterGrid
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import f1_score, balanced_accuracy_score, accuracy_score
from sklearn.base import clone
import pandas as pd
import numpy as np

cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

param_grid = {
    "svm__C": [0.1, 1, 10, 100],
    "svm__gamma": ["scale", 0.001, 0.01, 0.1],
    "svm__class_weight": ["balanced", None],
}

base_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        probability=False,
        random_state=42,
    )),
])

# Reuse identical folds for every configuration.
folds = list(cv.split(X_dev, y_dev, groups_dev))
search_results = []

for config_number, params in enumerate(ParameterGrid(param_grid), start=1):
    fold_scores = []

    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = clone(base_pipeline).set_params(**params)

        X_train = X_dev.iloc[train_idx]
        X_val = X_dev.iloc[val_idx]
        y_train = y_dev.iloc[train_idx]
        y_val = y_dev.iloc[val_idx]

        model.fit(X_train, y_train)
        predictions = model.predict(X_val)

        fold_scores.append({
            "macro_f1": f1_score(
                y_val,
                predictions,
                labels=sorted(y_dev.unique()),
                average="macro",
                zero_division=0,
            ),
            "balanced_accuracy": balanced_accuracy_score(
                y_val, predictions
            ),
            "accuracy": accuracy_score(y_val, predictions),
        })

    row = dict(params)

    for metric in ["macro_f1", "balanced_accuracy", "accuracy"]:
        values = [score[metric] for score in fold_scores]
        row[f"{metric}_mean"] = float(np.mean(values))
        row[f"{metric}_std"] = float(np.std(values, ddof=1))

    search_results.append(row)

search_results_df = (
    pd.DataFrame(search_results)
    .sort_values(
        ["macro_f1_mean", "balanced_accuracy_mean"],
        ascending=False,
    )
    .reset_index(drop=True)
)

print("Configurations evaluated:", len(search_results_df))
print("\n=== TOP 10 CONFIGURATIONS ===")
display(search_results_df.head(10).round(4))

print("\n=== BEST CONFIGURATION ===")
display(search_results_df.head(1).round(4))

print("\nNo model files were saved or overwritten.")

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Configurations evaluated: 32

=== TOP 10 CONFIGURATIONS ===

,svm__C,svm__class_weight,svm__gamma,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,balanced,0.01,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275
1,10.0,balanced,scale,0.2423,0.0396,0.2914,0.0815,0.7555,0.0228
2,10.0,balanced,0.01,0.2419,0.0344,0.3140,0.0839,0.7244,0.0372
3,100.0,balanced,0.001,0.2417,0.0473,0.3378,0.1353,0.6782,0.0433
4,1.0,balanced,scale,0.2408,0.0304,0.3209,0.0812,0.7125,0.0412
5,1.0,balanced,0.01,0.2408,0.0333,0.3522,0.1057,0.6526,0.0508
6,100.0,balanced,scale,0.2318,0.0340,0.2691,0.0762,0.7674,0.0155
7,0.1,balanced,scale,0.2295,0.0232,0.3434,0.1137,0.6265,0.0775
8,100.0,NaN,0.01,0.2286,0.0265,0.2718,0.0726,0.7609,0.0283
9,10.0,balanced,0.001,0.2257,0.0345,0.3380,0.1152,0.6093,0.0705

=== BEST CONFIGURATION ===

,svm__C,svm__class_weight,svm__gamma,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,balanced,0.01,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275

No model files were saved or overwritten.

In [7]:

print("Configurations evaluated:", len(search_results_df))

print("\n=== TOP 10 SVM CONFIGURATIONS ===")
display(
    search_results_df[
        [
            "svm__C",
            "svm__gamma",
            "svm__class_weight",
            "macro_f1_mean",
            "macro_f1_std",
            "balanced_accuracy_mean",
            "balanced_accuracy_std",
            "accuracy_mean",
            "accuracy_std",
        ]
    ].head(10).round(4)
)

print("\n=== BEST CONFIGURATION ===")
display(search_results_df.head(1).round(4))

Configurations evaluated: 32

=== TOP 10 SVM CONFIGURATIONS ===

,svm__C,svm__gamma,svm__class_weight,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,0.01,balanced,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275
1,10.0,scale,balanced,0.2423,0.0396,0.2914,0.0815,0.7555,0.0228
2,10.0,0.01,balanced,0.2419,0.0344,0.3140,0.0839,0.7244,0.0372
3,100.0,0.001,balanced,0.2417,0.0473,0.3378,0.1353,0.6782,0.0433
4,1.0,scale,balanced,0.2408,0.0304,0.3209,0.0812,0.7125,0.0412
5,1.0,0.01,balanced,0.2408,0.0333,0.3522,0.1057,0.6526,0.0508
6,100.0,scale,balanced,0.2318,0.0340,0.2691,0.0762,0.7674,0.0155
7,0.1,scale,balanced,0.2295,0.0232,0.3434,0.1137,0.6265,0.0775
8,100.0,0.01,NaN,0.2286,0.0265,0.2718,0.0726,0.7609,0.0283
9,10.0,0.001,balanced,0.2257,0.0345,0.3380,0.1152,0.6093,0.0705

=== BEST CONFIGURATION ===

,svm__C,svm__class_weight,svm__gamma,macro_f1_mean,macro_f1_std,balanced_accuracy_mean,balanced_accuracy_std,accuracy_mean,accuracy_std
0,100.0,balanced,0.01,0.2484,0.0427,0.3017,0.0947,0.7525,0.0275

In [8]:

from sklearn.base import clone
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
)
import pandas as pd
import numpy as np

best_params = search_results_df.iloc[0][
    ["svm__C", "svm__gamma", "svm__class_weight"]
].to_dict()

# Normalize values to their intended sklearn types.
best_params["svm__C"] = float(best_params["svm__C"])
best_params["svm__gamma"] = best_params["svm__gamma"]
best_params["svm__class_weight"] = best_params["svm__class_weight"]

models_to_compare = {
    "Baseline": {
        "svm__C": 1.0,
        "svm__gamma": "scale",
        "svm__class_weight": "balanced",
    },
    "Best tuned": best_params,
}

comparison_rows = []
all_labels = sorted(y_dev.unique())

for model_name, params in models_to_compare.items():
    for fold_number, (train_idx, val_idx) in enumerate(folds, start=1):
        model = clone(base_pipeline).set_params(**params)

        model.fit(X_dev.iloc[train_idx], y_dev.iloc[train_idx])
        predictions = model.predict(X_dev.iloc[val_idx])
        actual = y_dev.iloc[val_idx]

        comparison_rows.append({
            "model": model_name,
            "fold": fold_number,
            "macro_f1": f1_score(
                actual, predictions,
                labels=all_labels,
                average="macro",
                zero_division=0,
            ),
            "balanced_accuracy": balanced_accuracy_score(
                actual, predictions,
            ),
            "accuracy": accuracy_score(actual, predictions),
        })

comparison_df = pd.DataFrame(comparison_rows)

print("=== SAME-FOLD COMPARISON ===")
display(comparison_df.round(4))

print("\n=== MEAN AND STANDARD DEVIATION ===")
display(
    comparison_df.groupby("model")[
        ["macro_f1", "balanced_accuracy", "accuracy"]
    ].agg(["mean", "std"]).round(4)
)

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

=== SAME-FOLD COMPARISON ===

        model  fold  macro_f1  balanced_accuracy  accuracy
0    Baseline     1    0.2552             0.3908    0.6791
1    Baseline     2    0.2614             0.3401    0.7585
2    Baseline     3    0.2059             0.2319    0.6998
3  Best tuned     1    0.2915             0.4030    0.7537
4  Best tuned     2    0.2476             0.2865    0.7793
5  Best tuned     3    0.2061             0.2154    0.7244

=== MEAN AND STANDARD DEVIATION ===

           macro_f1         balanced_accuracy         accuracy
               mean     std              mean     std     mean     std
model
Baseline     0.2408  0.0304            0.3209  0.0812   0.7125  0.0412
Best tuned   0.2484  0.0427            0.3017  0.0947   0.7525  0.0275

In [9]:

from sklearn.base import clone
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    balanced_accuracy_score,
    accuracy_score,
)
import pandas as pd
import numpy as np

all_labels = sorted(y_dev.unique())

models_to_evaluate = {
    "Baseline": {
        "svm__C": 1.0,
        "svm__gamma": "scale",
        "svm__class_weight": "balanced",
    },
    "Tuned": {
        "svm__C": 100.0,
        "svm__gamma": 0.01,
        "svm__class_weight": "balanced",
    },
}

oof_results = {}

for model_name, params in models_to_evaluate.items():
    y_true_all = []
    y_pred_all = []

    for train_idx, val_idx in folds:
        model = clone(base_pipeline).set_params(**params)

        model.fit(X_dev.iloc[train_idx], y_dev.iloc[train_idx])
        predictions = model.predict(X_dev.iloc[val_idx])

        y_true_all.extend(y_dev.iloc[val_idx].tolist())
        y_pred_all.extend(predictions.tolist())

    y_true_all = np.asarray(y_true_all)
    y_pred_all = np.asarray(y_pred_all)
    oof_results[model_name] = (y_true_all, y_pred_all)

    print(f"\n{'=' * 20} {model_name} SVM {'=' * 20}")
    print("Pooled out-of-fold accuracy:",
          round(accuracy_score(y_true_all, y_pred_all), 4))
    print("Pooled out-of-fold balanced accuracy:",
          round(balanced_accuracy_score(y_true_all, y_pred_all), 4))
    print("Pooled out-of-fold macro-F1:",
          round(f1_score(
              y_true_all, y_pred_all,
              labels=all_labels,
              average="macro",
              zero_division=0,
          ), 4))

    print("\nClassification report:")
    print(classification_report(
        y_true_all,
        y_pred_all,
        labels=all_labels,
        zero_division=0,
    ))

    print("Confusion matrix (rows=true, columns=predicted):")
    display(pd.DataFrame(
        confusion_matrix(y_true_all, y_pred_all, labels=all_labels),
        index=all_labels,
        columns=all_labels,
    ))

print("\nNo model files were saved or overwritten.")

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

==================== Baseline SVM ====================
Pooled out-of-fold accuracy: 0.7125
Pooled out-of-fold balanced accuracy: 0.2796
Pooled out-of-fold macro-F1: 0.2482

Classification report:
                precision    recall  f1-score   support

        Asthma       0.00      0.00      0.00         6
Bronchiectasis       0.22      0.28      0.25        90
 Bronchiolitis       0.00      0.00      0.00        74
          COPD       0.93      0.81      0.87      3220
       Healthy       0.30      0.57      0.40       147
          LRTI       0.00      0.00      0.00        32
     Pneumonia       0.22      0.38      0.28       285
          URTI       0.19      0.20      0.20       171

      accuracy                           0.71      4025
     macro avg       0.23      0.28      0.25      4025
  weighted avg       0.78      0.71      0.74      4025

Confusion matrix (rows=true, columns=predicted):

,Asthma,Bronchiectasis,Bronchiolitis,COPD,Healthy,LRTI,Pneumonia,URTI
Asthma,0,0,0,0,3,0,0,3
Bronchiectasis,0,25,2,61,0,0,0,2
Bronchiolitis,0,8,0,8,10,0,7,41
COPD,0,79,55,2618,106,9,327,26
Healthy,0,0,5,7,84,6,15,30
LRTI,0,0,1,2,7,0,9,13
Pneumonia,0,0,34,78,32,7,107,27
URTI,1,1,29,38,36,18,14,34

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

==================== Tuned SVM ====================
Pooled out-of-fold accuracy: 0.7525
Pooled out-of-fold balanced accuracy: 0.2614
Pooled out-of-fold macro-F1: 0.256

Classification report:
                precision    recall  f1-score   support

        Asthma       0.00      0.00      0.00         6
Bronchiectasis       0.27      0.26      0.26        90
 Bronchiolitis       0.00      0.00      0.00        74
          COPD       0.90      0.88      0.89      3220
       Healthy       0.36      0.49      0.42       147
          LRTI       0.00      0.00      0.00        32
     Pneumonia       0.22      0.25      0.23       285
          URTI       0.28      0.22      0.25       171

      accuracy                           0.75      4025
     macro avg       0.25      0.26      0.26      4025
  weighted avg       0.76      0.75      0.76      4025

Confusion matrix (rows=true, columns=predicted):

,Asthma,Bronchiectasis,Bronchiolitis,COPD,Healthy,LRTI,Pneumonia,URTI
Asthma,0,0,0,0,2,0,0,4
Bronchiectasis,0,23,0,67,0,0,0,0
Bronchiolitis,0,8,0,15,6,0,11,34
COPD,0,49,49,2826,60,5,211,20
Healthy,0,0,4,25,72,6,17,23
LRTI,0,0,1,1,9,0,8,13
Pneumonia,0,0,26,161,24,2,70,2
URTI,1,4,29,56,25,12,6,38

No model files were saved or overwritten.

In [10]:

from pathlib import Path
import json

notebook_path = (
    Path.cwd().parent
    / "Notebooks"
    / "09_classical_ml.ipynb"
)

if not notebook_path.exists():
    print("Original notebook not found at:", notebook_path)
    print("Please check the path to Notebooks/09_classical_ml.ipynb.")
else:
    notebook_data = json.loads(
        notebook_path.read_text(encoding="utf-8")
    )

    print("=== FEATURE SELECTION / SCALING / SPLITTING CODE ===")

    keywords = [
        "selectkbest",
        "feature_selection",
        "selected_features",
        "mutual_info",
        "f_classif",
        "train_test_split",
        "standardscaler",
        "fit_transform",
        "feature_importances_",
    ]

    for cell_number, cell in enumerate(
        notebook_data["cells"]
    ):
        if cell["cell_type"] != "code":
            continue

        source = "".join(cell.get("source", []))
        if any(word in source.lower() for word in keywords):
            print(f"\n--- Cell {cell_number} ---")
            print(source[:5000])

=== FEATURE SELECTION / SCALING / SPLITTING CODE ===

--- Cell 1 ---

required_objects = [
    "PROJECT_ROOT",
    "train_df",
    "test_df",
    "selected_features_df",
    "selected_feature_names",
    "X_train",
    "X_test",
    "scaler",
    "X_train_scaled",
    "X_test_scaled",
    "label_encoder",
    "y_train",
    "y_test",
    "logistic_model",
    "svm_model",
    "rf_model",
]

status = []

for name in required_objects:
    exists = name in globals()
    obj = globals().get(name) if exists else None

    status.append({
        "variable": name,
        "available": exists,
        "type": type(obj).__name__ if exists else "NOT AVAILABLE",
    })

import pandas as pd
display(pd.DataFrame(status))


--- Cell 2 ---
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print("Imports completed.")

--- Cell 3 ---
PROJECT_ROOT = Path("/Users/vs/Sem 5/Respiratory-Disease-Classification")

FEATURES_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "features"
    / "respiratory_cycle_features.csv"
)

SELECTED_FEATURES_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "feature_selection"
    / "selected_features.csv"
)

RECORDINGS_PATH = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "recordings.csv"
)

features_df = pd.read_csv(FEATURES_PATH)
selected_features_df = pd.read_csv(SELECTED_FEATURES_PATH)
recordings_df = pd.read_csv(RECORDINGS_PATH)

print("Feature dataset shape:", features_df.shape)
print("Selected features shape:", selected_features_df.shape)
print("Recordings shape:", recordings_df.shape)

print("\nSelected feature columns:")
print(selected_features_df.columns.tolist())

--- Cell 6 ---
for name in [
    "PROJECT_ROOT",
    "train_df",
    "test_df",
    "selected_features_df",
]:
    print(name, name in globals())

--- Cell 7 ---
label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(train_df["diagnosis"])
y_test = label_encoder.transform(test_df["diagnosis"])

class_names = label_encoder.classes_

print("Disease classes:")
print(class_names)

print("\nNumber of classes:", len(class_names))

print("\nEncoded training labels:")
print(np.bincount(y_train))

print("\nEncoded testing labels:")
print(np.bincount(y_test))

--- Cell 8 ---
selected_feature_names = selected_features_df["feature"].tolist()

X_train = train_df[selected_feature_names].copy()
X_test = test_df[selected_feature_names].copy()

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("Number of selected features:", len(selected_feature_names))

print("\nMissing values:")
print("Train:", X_train.isna().sum().sum())
print("Test :", X_test.isna().sum().sum())

print("\nInfinite values:")
print("Train:", np.isinf(X_train.to_numpy()).sum())
print("Test :", np.isinf(X_test.to_numpy()).sum())

--- Cell 9 ---
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape :", X_test_scaled.shape)

print("\nTraining scaled mean:")
print(np.mean(X_train_scaled, axis=0)[:10])

print("\nTraining scaled standard deviation:")
print(np.std(X_train_scaled, axis=0)[:10])

--- Cell 13 ---

required = [
    "train_df",
    "test_df",
    "selected_features_df",
    "selected_feature_names",
    "scaler",
    "label_encoder",
    "logistic_model",
    "svm_model",
    "rf_model",
]

missing = [name for name in required if name not in globals()]

if missing:
    raise RuntimeError(f"Missing variables: {missing}")

print("Training objects are available.")
print("Training rows:", len(train_df))
print("Test rows:", len(test_df))
print("Selected features:", len(selected_feature_names))
print("Classes:", list(label_encoder.classes_))

assert len(train_df) == 4142, "Unexpected training row count"
assert len(test_df) == 2756, "Unexpected test row count"
assert len(selected_feature_names) == 33, "Unexpected feature count"


--- Cell 14 ---

from pathlib import Path
import json
import joblib
import sklearn
import pandas as pd

# Resolve the project root using the existing notebook variable.
project_root = Path(PROJECT_ROOT)
save_dir = project_root / "models" / "traditional_ml"
save_dir.mkdir(parents=True, exist_ok=True)

# Save the fitted estimators.
models_to_save = {
    "logistic_regression": logistic_model,
    "svm": svm_model,
    "random_forest": rf_model,
}

for model_name, model in models_to_save.items():
    output_path = save_dir / f"{model_name}.joblib"
    joblib.dump(model, output_path)
    print(f"Saved {model_name}: {output_path}")

# Save the shared preprocessing objects.
joblib.dump(scaler, save_dir / "scaler.joblib")
joblib.dump(label_encoder, save_dir / "label_encoder.joblib")

# Save feature order and metadata.
metadata = {
    "project": "Respiratory Disease Classification",
    "source_notebook": "notebooks/09_classical_ml.ipynb",
    "training_rows": int(len(train_df)),
    "test_rows": int(len(test_df)),
    "feature_count": int(len(selected_feature_names)),
    "selected_feature_names": list(selected_feature_names),
    "class_names": [str(c) for c in label_encoder.classes_],
    "scaler_used": {
        "logistic_regression": True,
        "svm": True,
        "random_forest": False,
    },
    "training_split": "Existing official_split; unchanged",
    "sklearn_version": sklearn.__version__,
    "models": {
        "logistic_regression": {
            "file": "logistic_regression.joblib",
            "class": type(logistic_model).__name__,
            "parameters": logistic_model.get_params(),
        },
        "svm": {
            "file": "svm.joblib",
            "class": type(svm_model).__name__,
            "parameters": svm_model.get_params(),
        },
        "random_forest": {
            "file": "random_forest.joblib",
            "class": type(rf_model).__name__,
            "parameters": rf_model.get_params(),
        },
    },
}

with open(save_dir / "classical_ml_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2, default=str)

# Save the ordered feature list separately for convenient inspection.
with open(save_dir / "selected_features.json", "w") as f:
    json.dump(list(selected_feature_names), f, indent=2)

print("\nSaved preprocessing and metadata.")
print("Output directory:", save_dir)
print("Files:")
for path in sorted(save_dir.iterdir()):
    if path.is_file():
        print(f"  {path.name} ({path.stat().st_size:,} bytes)")


--- Cell 21 ---
# ============================================================
# NOTEBOOK 09 — STEP 4
# RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. EXTRACT RANDOM FOREST FEATURE IMPORTANCE
# ------------------------------------------------------------

rf_importance_df = pd.DataFrame({
    "feature": selected_feature_names,
    "importance": rf_model.feature_importances_
})

rf_importance_df = rf_importance_df.sort_values(
    by="importance",
    ascending=False
).reset_index(drop=True)


# ------------------------------------------------------------
# 2. DISPLAY ALL FEATURES
# ------------------------------------------------------------

print("=" * 80)
print("RANDOM FOREST FEATURE IMPORTANCE")
print("=" * 80)

display(
    rf_importance_df.style.format({
        "importance": "{:.6f}"
    })
)


# ------------------------------------------------------------
# 3. TOP 15 FEATURES
# ------------------------------------------------------------

top_15_rf = rf_importance_df.head(15)

print("\n" + "=" * 80)
print("TOP 15 RANDOM FOREST FEATURES")
print("=" * 80)

display(
    top_15_rf.style.format({
        "importance": "{:.6f}"
    })
)


# ------------------------------------------------------------
# 4. PLOT TOP 15 FEATURES
# ------------------------------------------------------------

plot_df = top_15_rf.sort_values(
    by="importance",
    ascending=True
)

plt.figure(figsize=(10, 7))

plt.barh(
    plot_df["feature"],
    plot_df["importance"]
)

plt.xlabel("Random Forest Importance")
plt.ylabel("Feature")
plt.title("Top 15 Random Forest Feature Importances")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 5. FEATURE GROUP SUMMARY
# ------------------------------------------------------------

def get_feature_group(feature):

    if feature.startswith("mfcc_"):
        return "MFCC"

    if feature.startswith("wavelet_"):
        return "Wavelet"

    if feature.startswith("band_energy_"):
        return "Band Energy"

    if feature in [
        "mean",
        "std",
        "variance",
        "rms",
        "max",
        "min",
        "peak_to_peak",
        "median",
        "skewness",
        "kurtosis",
        "zero_crossing_rate",
        "energy"
    ]:
        return "Time Domain"

    if feature in [
        "spectral_centroid",
        "spectral_bandwidth",
        "spectral_rolloff",
        "spectral_flatness",
        "spectral_energy",
        "dominant_frequency",
        "spectral_entropy"
    ]:
        return "Spectral"

    return "Other"


rf_importance_df["feature_group"] = (
    rf_importance_df["feature"]
    .apply(get_feature_group)
)

group_importance = (
    rf_importance_df
    .groupby("feature_group")["importance"]
    .agg(["sum", "mean", "count"])
    .sort_values("sum", ascending=False)
)

print("\n" + "=" * 80)
print("RANDOM FOREST IMPORTANCE BY FEATURE GROUP")
print("=" * 80)

display(
    group_importance.style.format({
        "sum": "{:.6f}",
        "mean": "{:.6f}"
    })
)

--- Cell 22 ---
# ============================================================
# NOTEBOOK 09 — STEP 5
# SAVE ALL CLASSICAL ML RESULTS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. CREATE OUTPUT DIRECTORY
# ------------------------------------------------------------

CLASSICAL_ML_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "classical_ml"
)

CLASSICAL_ML_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ------------------------------------------------------------
# 2. SAVE MODEL COMPARISON
# ------------------------------------------------------------

results_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_model_comparison.csv",
    index=False
)


# ------------------------------------------------------------
# 3. SAVE PER-DISEASE RESULTS
# ------------------------------------------------------------

per_class_results_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_per_disease_results.csv",
    index=False
)


# ------------------------------------------------------------
# 4. SAVE RANDOM FOREST FEATURE IMPORTANCE
# ------------------------------------------------------------

rf_importance_df.to_csv(
    CLASSICAL_ML_DIR / "random_forest_feature_importance.csv",
    index=False
)


# ------------------------------------------------------------
# 5. SAVE FEATURE-GROUP IMPORTANCE
# ------------------------------------------------------------

group_importance.reset_index().to_csv(
    CLASSICAL_ML_DIR / "random_forest_feature_group_importance.csv",
    index=False
)


# ------------------------------------------------------------
# 6. SAVE SELECTED FEATURES USED BY THE MODELS
# ------------------------------------------------------------

pd.DataFrame({
    "feature": selected_feature_names
}).to_csv(
    CLASSICAL_ML_DIR / "classical_ml_selected_features.csv",
    index=False
)


# ------------------------------------------------------------
# 7. SAVE MODEL PREDICTIONS
# ------------------------------------------------------------

prediction_df = pd.DataFrame({
    "patient_id": test_df["patient_id"].values,
    "recording_id": test_df["recording_id"].values,
    "chest_location": test_df["chest_location"].values,
    "true_diagnosis": test_df["diagnosis"].values,

    "logistic_regression_prediction":
        label_encoder.inverse_transform(logistic_predictions),

    "svm_prediction":
        label_encoder.inverse_transform(svm_predictions),

    "random_forest_prediction":
        label_encoder.inverse_transform(rf_predictions)
})

prediction_df.to_csv(
    CLASSICAL_ML_DIR / "classical_ml_predictions.csv",
    index=False
)


# ------------------------------------------------------------
# 8. FINAL VALIDATION
# ------------------------------------------------------------

saved_files = sorted(
    CLASSICAL_ML_DIR.glob("*.csv")
)

print("=" * 80)
print("NOTEBOOK 09 — CLASSICAL ML RESULTS SAVED")
print("=" * 80)

for file_path in saved_files:
    print(file_path.name)

print("\nOutput directory:")
print(CLASSICAL_ML_DIR)

print("\nModel comparison:")
display(results_df)

print("\nBest model by macro F1:")
best_model = results_df.iloc[0]

print("Model:", best_model["model"])
print("Macro F1:", round(best_model["macro_f1"], 4))
print("Balanced Accuracy:", round(
    best_model["balanced_accuracy"], 4
))
print("Accuracy:", round(
    best_model["accuracy"], 4
))

print("\n" + "=" * 80)
print("NOTEBOOK 09 VALIDATION COMPLETE")
print("=" * 80)

In [11]:

from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent

notebook07_features_path = (
    project_root
    / "data"
    / "processed"
    / "feature_selection"
    / "selected_features.csv"
)

svm_features_path = (
    project_root
    / "data"
    / "processed"
    / "classical_ml"
    / "classical_ml_selected_features.csv"
)

print("Notebook 07 feature list exists:", notebook07_features_path.exists())
print("SVM feature list exists:", svm_features_path.exists())

if notebook07_features_path.exists() and svm_features_path.exists():
    features_07 = pd.read_csv(notebook07_features_path)["feature"].astype(str).tolist()
    features_svm = pd.read_csv(svm_features_path)["feature"].astype(str).tolist()

    set_07 = set(features_07)
    set_svm = set(features_svm)

    print("\nNotebook 07 feature count:", len(features_07))
    print("SVM feature count:", len(features_svm))
    print("Same features, ignoring order:", set_07 == set_svm)
    print("Same features in same order:", features_07 == features_svm)

    print("\nFeatures only in Notebook 07 list:")
    print(sorted(set_07 - set_svm))

    print("\nFeatures only in SVM list:")
    print(sorted(set_svm - set_07))

    print("\nDuplicate names in Notebook 07 list:",
          len(features_07) - len(set_07))
    print("Duplicate names in SVM list:",
          len(features_svm) - len(set_svm))
else:
    print("\nPlease check the missing file path before proceeding.")

Notebook 07 feature list exists: True
SVM feature list exists: True

Notebook 07 feature count: 33
SVM feature count: 33
Same features, ignoring order: True
Same features in same order: True

Features only in Notebook 07 list:
[]

Features only in SVM list:
[]

Duplicate names in Notebook 07 list: 0
Duplicate names in SVM list: 0

In [12]:

from pathlib import Path
import json

project_root = Path.cwd().parent
notebook07_path = project_root / "Notebooks" / "07_feature_selection.ipynb"

print("Notebook path:", notebook07_path)
print("Exists:", notebook07_path.exists())

if notebook07_path.exists():
    notebook = json.loads(
        notebook07_path.read_text(encoding="utf-8")
    )

    for i, cell in enumerate(notebook["cells"]):
        if cell["cell_type"] != "code":
            continue

        source = "".join(cell.get("source", []))
        keywords = [
            "mutual_info",
            "f_classif",
            "feature_importances_",
            "correlation_threshold",
            "selected_features",
            "consensus",
        ]

        if any(keyword in source.lower() for keyword in keywords):
            print(f"\n{'=' * 18} CELL {i} {'=' * 18}")
            print(source[:7000])
else:
    print("Check the notebook location before proceeding.")

Notebook path: /Users/vs/Sem 5/Respiratory-Disease-Classification/Notebooks/07_feature_selection.ipynb
Exists: True

================== CELL 1 ==================
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_selection import (
    f_classif,
    mutual_info_classif
)

from sklearn.ensemble import RandomForestClassifier

from sklearn.preprocessing import LabelEncoder

print("Libraries imported successfully.")

================== CELL 11 ==================
# ============================================================
# ANOVA F-score
# ============================================================

anova_scores, anova_pvalues = f_classif(
    X_train,
    y_train
)

anova_df = pd.DataFrame({
    "feature": feature_columns,
    "anova_f_score": anova_scores,
    "anova_p_value": anova_pvalues
})

anova_df = anova_df.sort_values(
    "anova_f_score",
    ascending=False
).reset_index(drop=True)

display(anova_df)

================== CELL 14 ==================
# ============================================================
# Mutual Information
# ============================================================

mi_scores = mutual_info_classif(
    X_train,
    y_train,
    random_state=42
)

mi_df = pd.DataFrame({
    "feature": feature_columns,
    "mutual_information": mi_scores
})

mi_df = mi_df.sort_values(
    "mutual_information",
    ascending=False
).reset_index(drop=True)

display(mi_df)

================== CELL 16 ==================
plt.figure(figsize=(10, 6))

plt.barh(
    top_mi["feature"][::-1],
    top_mi["mutual_information"][::-1]
)

plt.xlabel("Mutual Information")
plt.ylabel("Feature")
plt.title(
    "Top 15 Features by Mutual Information"
)

plt.tight_layout()
plt.show()

================== CELL 17 ==================
# ============================================================
# Random Forest Feature Importance
# ============================================================

rf_selector = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

rf_selector.fit(
    X_train,
    y_train
)

rf_importance_df = pd.DataFrame({
    "feature": feature_columns,
    "rf_importance": rf_selector.feature_importances_
})

rf_importance_df = rf_importance_df.sort_values(
    "rf_importance",
    ascending=False
).reset_index(drop=True)

display(rf_importance_df)

================== CELL 21 ==================
feature_ranking_df["anova_rank"] = (
    feature_ranking_df[
        "anova_f_score"
    ]
    .rank(
        ascending=False,
        method="min"
    )
)

feature_ranking_df["mi_rank"] = (
    feature_ranking_df[
        "mutual_information"
    ]
    .rank(
        ascending=False,
        method="min"
    )
)

feature_ranking_df["rf_rank"] = (
    feature_ranking_df[
        "rf_importance"
    ]
    .rank(
        ascending=False,
        method="min"
    )
)

================== CELL 24 ==================
# ============================================================
# Normalized Consensus Score
# ============================================================

feature_ranking_df["anova_score_norm"] = (
    feature_ranking_df["anova_rank"].max()
    - feature_ranking_df["anova_rank"]
    + 1
) / feature_ranking_df["anova_rank"].max()

feature_ranking_df["mi_score_norm"] = (
    feature_ranking_df["mi_rank"].max()
    - feature_ranking_df["mi_rank"]
    + 1
) / feature_ranking_df["mi_rank"].max()

feature_ranking_df["rf_score_norm"] = (
    feature_ranking_df["rf_rank"].max()
    - feature_ranking_df["rf_rank"]
    + 1
) / feature_ranking_df["rf_rank"].max()

feature_ranking_df["consensus_score"] = (
    feature_ranking_df[
        [
            "anova_score_norm",
            "mi_score_norm",
            "rf_score_norm"
        ]
    ]
    .mean(axis=1)
)

feature_ranking_df = (
    feature_ranking_df
    .sort_values(
        "consensus_score",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    feature_ranking_df[
        [
            "feature",
            "anova_f_score",
            "mutual_information",
            "rf_importance",
            "anova_rank",
            "mi_rank",
            "rf_rank",
            "average_rank",
            "consensus_score"
        ]
    ]
)

================== CELL 25 ==================
top_consensus = feature_ranking_df.head(20)

plt.figure(figsize=(11, 7))

plt.barh(
    top_consensus["feature"][::-1],
    top_consensus["consensus_score"][::-1]
)

plt.xlabel("Consensus Score")
plt.ylabel("Feature")
plt.title(
    "Top 20 Features — Combined Feature Selection Ranking"
)

plt.tight_layout()
plt.show()

================== CELL 27 ==================
# ============================================================
# Redundancy-Aware Feature Selection
# ============================================================

ranked_features = feature_ranking_df[
    "feature"
].tolist()

selection_corr_threshold = 0.90

selected_features = []

for feature in ranked_features:

    if len(selected_features) == 0:
        selected_features.append(feature)
        continue

    correlations = (
        train_correlation_matrix.loc[
            feature,
            selected_features
        ].abs()
    )

    if correlations.max() < selection_corr_threshold:
        selected_features.append(feature)


print("Original number of features:", len(feature_columns))
print("Selected number of features:", len(selected_features))

print("\nSelected features:")

for i, feature in enumerate(selected_features, start=1):
    print(f"{i:02d}. {feature}")

================== CELL 28 ==================
# ============================================================
# Final Feature Selection Table
# ============================================================

final_feature_selection_df = (
    feature_ranking_df[
        feature_ranking_df["feature"].isin(
            selected_features
        )
    ]
    .copy()
)

final_feature_selection_df = (
    final_feature_selection_df
    .sort_values(
        "consensus_score",
        ascending=False
    )
    .reset_index(drop=True)
)

display(final_feature_selection_df)

================== CELL 29 ==================
selected_features_df = pd.DataFrame({
    "feature": selected_features
})

selected_features_df.to_csv(
    feature_selection_dir / "selected_features.csv",
    index=False
)

final_feature_selection_df.to_csv(
    feature_selection_dir /
    "final_feature_selection_ranking.csv",
    index=False
)

print("Selected feature list saved successfully.")

================== CELL 30 ==================
# ============================================================
# Recreate Reduced Training/Test Feature Matrices
# ============================================================

X_train_selected = train_df[
    selected_features
].copy()

X_test_selected = test_df[
    selected_features
].copy()

print("Original training feature shape:", X_train.shape)
print("Selected training feature shape:", X_train_selected.shape)

print("\nSelected testing feature shape:", X_test_selected.shape)

================== CELL 31 ==================
# ============================================================
# Final Feature Selection Validation
# ============================================================

print("========== NOTEBOOK 07 VALIDATION ==========")

print("Original feature count:", len(feature_columns))
print("Selected feature count:", len(selected_features))

print("\nSelected features:")
for i, feature in enumerate(selected_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nTraining matrix shape:", X_train_selected.shape)
print("Testing matrix shape:", X_test_selected.shape)

print(
    "\nMissing values - train:",
    X_train_selected.isna().sum().sum()
)

print(
    "Missing values - test:",
    X_test_selected.isna().sum().sum()
)

print(
    "Infinite values - train:",
    np.isinf(X_train_selected.to_numpy()).sum()
)

print(
    "Infinite values - test:",
    np.isinf(X_test_selected.to_numpy()).sum()
)

print("\nNotebook 07 feature selection complete.")

================== CELL 32 ==================
selected_features_df = pd.DataFrame({
    "feature": selected_features
})

selected_features_df.to_csv(
    feature_selection_dir / "selected_features.csv",
    index=False
)

print("Selected feature list saved successfully.")

================== CELL 33 ==================
# ============================================================
# Final Feature Selection Validation
# ============================================================

print("========== NOTEBOOK 07 VALIDATION ==========")

print("Original feature count:", len(feature_columns))
print("Selected feature count:", len(selected_features))

print("\nSelected features:")
for i, feature in enumerate(selected_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nTraining matrix shape:", X_train_selected.shape)
print("Testing matrix shape:", X_test_selected.shape)

print(
    "\nMissing values - train:",
    X_train_selected.isna().sum().sum()
)

print(
    "Missing values - test:",
    X_test_selected.isna().sum().sum()
)

print(
    "Infinite values - train:",
    np.isinf(X_train_selected.to_numpy()).sum()
)

print(
    "Infinite values - test:",
    np.isinf(X_test_selected.to_numpy()).sum()
)

print("\nNotebook 07 feature selection complete.")

In [13]:

from pathlib import Path
import pandas as pd
import numpy as np

project_root = Path.cwd().parent

FEATURES_PATH = (
    project_root
    / "data"
    / "processed"
    / "features"
    / "respiratory_cycle_features.csv"
)

features_df = pd.read_csv(FEATURES_PATH)

metadata_columns = {
    "patient_id",
    "recording_id",
    "chest_location",
    "diagnosis",
    "disease_label",
    "official_split",
    "audio_path",
    "wav_path",
}

candidate_features = [
    col for col in features_df.columns
    if col not in metadata_columns
    and pd.api.types.is_numeric_dtype(features_df[col])
]

print("Feature table shape:", features_df.shape)
print("Numeric candidate features:", len(candidate_features))
print("\nCandidate feature names:")
for i, name in enumerate(candidate_features, start=1):
    print(f"{i:02d}. {name}")

print("\nMissing values across candidate features:",
      int(features_df[candidate_features].isna().sum().sum()))

candidate_values = features_df[candidate_features].to_numpy(dtype=float)
print("Infinite values across candidate features:",
      int(np.isinf(candidate_values).sum()))

print("\nCurrent SVM selected features:", len(selected_features))
print("All current selected features exist in candidate pool:",
      set(selected_features).issubset(set(candidate_features)))

Feature table shape: (6898, 52)
Numeric candidate features: 44

Candidate feature names:
01. cycle_number
02. start_time
03. end_time
04. crackles
05. wheezes
06. mean
07. std
08. variance
09. rms
10. max
11. min
12. peak_to_peak
13. median
14. skewness
15. kurtosis
16. energy
17. zero_crossing_rate
18. spectral_centroid
19. spectral_bandwidth
20. spectral_rolloff
21. spectral_flatness
22. spectral_energy
23. dominant_frequency
24. spectral_entropy
25. band_energy_0_500
26. band_energy_500_1000
27. band_energy_1000_1500
28. band_energy_1500_2000
29. mfcc_1_mean
30. mfcc_2_mean
31. mfcc_3_mean
32. mfcc_4_mean
33. mfcc_5_mean
34. mfcc_6_mean
35. mfcc_7_mean
36. mfcc_8_mean
37. mfcc_9_mean
38. mfcc_10_mean
39. mfcc_11_mean
40. mfcc_12_mean
41. mfcc_13_mean
42. wavelet_energy
43. wavelet_entropy
44. wavelet_std

Missing values across candidate features: 0
Infinite values across candidate features: 0

Current SVM selected features: 33
All current selected features exist in candidate pool: True

In [14]:

from pathlib import Path
import json

project_root = Path.cwd().parent
notebook07_path = project_root / "Notebooks" / "07_feature_selection.ipynb"
notebook = json.loads(notebook07_path.read_text(encoding="utf-8"))

for i, cell in enumerate(notebook["cells"]):
    if cell["cell_type"] != "code":
        continue

    source = "".join(cell.get("source", []))
    if any(term in source for term in [
        "feature_columns =",
        "X_train =",
        "train_df =",
        "train_correlation_matrix =",
    ]):
        print(f"\n{'=' * 16} CELL {i} {'=' * 16}")
        print(source[:6000])

================ CELL 3 ================
metadata_columns = [
    "patient_id",
    "recording_id",
    "chest_location",
    "acquisition_mode",
    "equipment",
    "cycle_number",
    "start_time",
    "end_time",
    "sound_label",
    "crackles",
    "wheezes",
    "diagnosis",
    "processed_path",
]

feature_columns = [
    col
    for col in features_df.columns
    if col not in metadata_columns
]

print("Number of features:", len(feature_columns))

================ CELL 10 ================
# ============================================================
# Prepare Training Data for Feature Selection
# ============================================================

train_df = features_with_split[
    features_with_split["official_split"] == "train"
].copy()

test_df = features_with_split[
    features_with_split["official_split"] == "test"
].copy()

X_train = train_df[feature_columns].copy()

label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(
    train_df["diagnosis"]
)

print("Training cycles:", len(train_df))
print("Testing cycles:", len(test_df))
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

================ CELL 26 ================
# ============================================================
# Recreate Training Correlation Matrix
# ============================================================

train_correlation_matrix = X_train.corr()

print(
    "Training correlation matrix shape:",
    train_correlation_matrix.shape
)

In [15]:

metadata_columns = {
    "patient_id",
    "recording_id",
    "chest_location",
    "acquisition_mode",
    "equipment",
    "cycle_number",
    "start_time",
    "end_time",
    "sound_label",
    "crackles",
    "wheezes",
    "diagnosis",
    "processed_path",
    "disease_label",
    "official_split",
    "audio_path",
    "wav_path",
}

candidate_features = [
    col
    for col in development_features.columns
    if col not in metadata_columns
    and pd.api.types.is_numeric_dtype(development_features[col])
]

print("Candidate acoustic features:", len(candidate_features))
print("\nFeature names:")
for i, name in enumerate(candidate_features, start=1):
    print(f"{i:02d}. {name}")

print("\nCurrent selected features:", len(selected_features))
print(
    "All selected features belong to the candidate pool:",
    set(selected_features).issubset(set(candidate_features))
)

assert len(candidate_features) > 0
assert set(selected_features).issubset(set(candidate_features))
assert development_features[candidate_features].notna().all().all()

Candidate acoustic features: 39

Feature names:
01. mean
02. std
03. variance
04. rms
05. max
06. min
07. peak_to_peak
08. median
09. skewness
10. kurtosis
11. energy
12. zero_crossing_rate
13. spectral_centroid
14. spectral_bandwidth
15. spectral_rolloff
16. spectral_flatness
17. spectral_energy
18. dominant_frequency
19. spectral_entropy
20. band_energy_0_500
21. band_energy_500_1000
22. band_energy_1000_1500
23. band_energy_1500_2000
24. mfcc_1_mean
25. mfcc_2_mean
26. mfcc_3_mean
27. mfcc_4_mean
28. mfcc_5_mean
29. mfcc_6_mean
30. mfcc_7_mean
31. mfcc_8_mean
32. mfcc_9_mean
33. mfcc_10_mean
34. mfcc_11_mean
35. mfcc_12_mean
36. mfcc_13_mean
37. wavelet_energy
38. wavelet_entropy
39. wavelet_std

Current selected features: 33
All selected features belong to the candidate pool: True

In [16]:

import warnings
import numpy as np
import pandas as pd

from sklearn.feature_selection import f_classif, mutual_info_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    classification_report,
)

# Fixed order for consistent reporting across all folds
ALL_CLASSES = [
    "Asthma",
    "Bronchiectasis",
    "Bronchiolitis",
    "COPD",
    "Healthy",
    "LRTI",
    "Pneumonia",
    "URTI",
]

cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

# Confirm the data are ready
assert X_dev.shape[0] == len(y_dev) == len(groups_dev)
assert len(candidate_features) == 39
assert set(selected_features).issubset(candidate_features)
assert X_dev[candidate_features].notna().all().all()

print("Development samples:", len(X_dev))
print("Development patients:", groups_dev.nunique())
print("Candidate features:", len(candidate_features))
print("Existing selected features:", len(selected_features))
print("Validation folds: 3")
print("Feature selection will be performed independently within each fold.")

KeyError: "['std', 'variance', 'spectral_centroid', 'spectral_energy', 'wavelet_energy', 'wavelet_std'] not in index"

In [17]:

# Rebuild the development matrix using the complete 39-feature pool

missing_from_X_dev = [
    col for col in candidate_features
    if col not in X_dev.columns
]

print("Features missing from previous X_dev:", missing_from_X_dev)

X_dev = (
    development_features[candidate_features]
    .apply(pd.to_numeric, errors="coerce")
    .copy()
)

y_dev = development_features["diagnosis"].astype(str).copy()
groups_dev = development_features["patient_id"].astype(str).copy()

print("\nUpdated X_dev shape:", X_dev.shape)
print("Labels:", len(y_dev))
print("Unique patients:", groups_dev.nunique())
print("Missing values:", int(X_dev.isna().sum().sum()))
print("Infinite values:", int(np.isinf(X_dev.to_numpy(dtype=float)).sum()))

assert X_dev.shape == (4025, 39)
assert len(y_dev) == len(groups_dev) == 4025
assert X_dev.notna().all().all()
assert np.isfinite(X_dev.to_numpy(dtype=float)).all()
assert set(selected_features).issubset(set(X_dev.columns))

print("\nPASS: all 39 acoustic features are available.")

Features missing from previous X_dev: ['std', 'variance', 'spectral_centroid', 'spectral_energy', 'wavelet_energy', 'wavelet_std']

Updated X_dev shape: (4025, 39)
Labels: 4025
Unique patients: 77
Missing values: 0
Infinite values: 0

PASS: all 39 acoustic features are available.

In [19]:

from sklearn.feature_selection import f_classif, mutual_info_classif
from sklearn.ensemble import RandomForestClassifier

def select_features_within_fold(
    X_train_fold,
    y_train_fold,
    correlation_threshold=0.90,
    random_state=42,
):
    """
    Reproduce Notebook 07's consensus feature selection using
    only the current training fold.
    """
    X = X_train_fold[candidate_features].copy()
    y = pd.Series(y_train_fold, index=X.index)

    # 1. ANOVA scores
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        anova_scores, _ = f_classif(X, y)

    # 2. Mutual-information scores
    mi_scores = mutual_info_classif(
        X,
        y,
        random_state=random_state,
    )

    # 3. Random Forest importance
    rf = RandomForestClassifier(
        n_estimators=300,
        random_state=random_state,
        n_jobs=-1,
        class_weight="balanced",
    )
    rf.fit(X, y)
    rf_scores = rf.feature_importances_

    score_table = pd.DataFrame({
        "feature": candidate_features,
        "anova": np.nan_to_num(
            anova_scores, nan=0.0, posinf=0.0, neginf=0.0
        ),
        "mutual_information": np.nan_to_num(
            mi_scores, nan=0.0, posinf=0.0, neginf=0.0
        ),
        "random_forest": np.nan_to_num(
            rf_scores, nan=0.0, posinf=0.0, neginf=0.0
        ),
    })

    # 4. Rank descending, then combine normalized ranks
    for score_name in ["anova", "mutual_information", "random_forest"]:
        rank_name = f"{score_name}_rank"
        normalized_name = f"{score_name}_normalized"

        score_table[rank_name] = score_table[score_name].rank(
            ascending=False,
            method="min",
        )

        max_rank = score_table[rank_name].max()
        score_table[normalized_name] = (
            max_rank - score_table[rank_name] + 1
        ) / max_rank

    normalized_columns = [
        "anova_normalized",
        "mutual_information_normalized",
        "random_forest_normalized",
    ]

    score_table["consensus_score"] = score_table[
        normalized_columns
    ].mean(axis=1)

    score_table = score_table.sort_values(
        "consensus_score",
        ascending=False,
        kind="stable",
    ).reset_index(drop=True)

    # 5. Greedy redundancy filtering using training-fold correlations
    corr = X.corr().abs().fillna(0.0)
    selected = []

    for feature in score_table["feature"]:
        if not selected:
            selected.append(feature)
            continue

        max_correlation = corr.loc[feature, selected].max()

        if max_correlation < correlation_threshold:
            selected.append(feature)

    if not selected:
        raise ValueError("Feature selection returned no features.")

    return selected, score_table

In [20]:

from sklearn.model_selection import StratifiedGroupKFold

cv = StratifiedGroupKFold(
    n_splits=3,
    shuffle=True,
    random_state=42,
)

# Get the first patient-grouped fold
train_idx, val_idx = next(
    cv.split(X_dev, y_dev, groups=groups_dev)
)

X_train_fold = X_dev.iloc[train_idx]
y_train_fold = y_dev.iloc[train_idx]
groups_train_fold = groups_dev.iloc[train_idx]

X_val_fold = X_dev.iloc[val_idx]
y_val_fold = y_dev.iloc[val_idx]
groups_val_fold = groups_dev.iloc[val_idx]

# Confirm there is no patient overlap
patient_overlap = set(groups_train_fold) & set(groups_val_fold)
assert len(patient_overlap) == 0, "Patient leakage detected!"

# Select features using only the training fold
fold_features, fold_ranking = select_features_within_fold(
    X_train_fold,
    y_train_fold,
    correlation_threshold=0.90,
    random_state=42,
)

print("Training cycles:", len(train_idx))
print("Validation cycles:", len(val_idx))
print("Training patients:", groups_train_fold.nunique())
print("Validation patients:", groups_val_fold.nunique())
print("Patient overlap:", len(patient_overlap))

print("\nSelected features:", len(fold_features))
print("Selected feature names:")
for i, feature in enumerate(fold_features, start=1):
    print(f"{i:02d}. {feature}")

print("\nTop 10 consensus-ranked features:")
display(
    fold_ranking[
        ["feature", "anova", "mutual_information",
         "random_forest", "consensus_score"]
    ].head(10).round(4)
)

assert len(fold_features) > 0
assert set(fold_features).issubset(set(candidate_features))

print("\nPASS: fold-specific feature selection completed.")

Training cycles: 2685
Validation cycles: 1340
Training patients: 55
Validation patients: 22
Patient overlap: 0

Selected features: 32
Selected feature names:
01. spectral_entropy
02. mfcc_11_mean
03. zero_crossing_rate
04. mfcc_13_mean
05. mfcc_1_mean
06. dominant_frequency
07. spectral_rolloff
08. wavelet_entropy
09. spectral_bandwidth
10. mfcc_5_mean
11. band_energy_500_1000
12. mfcc_4_mean
13. mfcc_3_mean
14. mfcc_2_mean
15. peak_to_peak
16. mfcc_8_mean
17. mfcc_9_mean
18. mfcc_12_mean
19. spectral_flatness
20. mfcc_7_mean
21. band_energy_1000_1500
22. mfcc_6_mean
23. min
24. energy
25. mfcc_10_mean
26. rms
27. band_energy_1500_2000
28. skewness
29. mean
30. kurtosis
31. median
32. max

Top 10 consensus-ranked features:

,feature,anova,mutual_information,random_forest,consensus_score
0,spectral_entropy,75.5738,0.2002,0.0828,0.9915
1,mfcc_11_mean,77.5060,0.1533,0.0424,0.9487
2,zero_crossing_rate,68.2651,0.1470,0.0433,0.9316
3,mfcc_13_mean,60.8032,0.1221,0.0375,0.8547
4,mfcc_1_mean,59.7319,0.1390,0.0352,0.8376
5,dominant_frequency,25.8082,0.1384,0.0580,0.8205
6,spectral_centroid,47.6043,0.1348,0.0319,0.7863
7,spectral_rolloff,33.6662,0.0986,0.0389,0.7692
8,wavelet_entropy,36.2845,0.1014,0.0310,0.7350
9,spectral_bandwidth,39.0945,0.0923,0.0285,0.7179

PASS: fold-specific feature selection completed.

In [21]:

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)

fold_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(
        kernel="rbf",
        C=1.0,
        gamma="scale",
        class_weight="balanced",
        probability=False,
        random_state=42,
    )),
])

# Train only on this fold's training patients and selected features
fold_model.fit(
    X_train_fold[fold_features],
    y_train_fold,
)

# Predict the unseen validation patients
fold_predictions = fold_model.predict(
    X_val_fold[fold_features]
)

print("Patient overlap:", len(set(groups_train_fold) & set(groups_val_fold)))
print("Features used:", len(fold_features))

print("\nFOLD 1 METRICS")
print("Accuracy:", round(accuracy_score(y_val_fold, fold_predictions), 4))
print(
    "Balanced accuracy:",
    round(balanced_accuracy_score(y_val_fold, fold_predictions), 4),
)
print(
    "Macro-F1:",
    round(
        f1_score(
            y_val_fold,
            fold_predictions,
            labels=ALL_CLASSES,
            average="macro",
            zero_division=0,
        ),
        4,
    ),
)
print(
    "Weighted-F1:",
    round(
        f1_score(
            y_val_fold,
            fold_predictions,
            average="weighted",
            zero_division=0,
        ),
        4,
    ),
)

print("\nClassification report:")
print(
    classification_report(
        y_val_fold,
        fold_predictions,
        labels=ALL_CLASSES,
        zero_division=0,
    ),
)

print("Confusion matrix (rows=true, columns=predicted):")
display(
    pd.DataFrame(
        confusion_matrix(
            y_val_fold,
            fold_predictions,
            labels=ALL_CLASSES,
        ),
        index=ALL_CLASSES,
        columns=ALL_CLASSES,
    )
)

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Patient overlap: 0
Features used: 32

FOLD 1 METRICS
Accuracy: 0.6791
Balanced accuracy: 0.3857
Macro-F1: 0.2519
Weighted-F1: 0.7277

Classification report:
                precision    recall  f1-score   support

        Asthma       0.00      0.00      0.00         0
Bronchiectasis       0.20      0.39      0.27        41
 Bronchiolitis       0.00      0.00      0.00        19
          COPD       0.94      0.77      0.85      1073
       Healthy       0.34      0.66      0.45        50
          LRTI       0.00      0.00      0.00         0
     Pneumonia       0.12      0.19      0.15        95
          URTI       0.29      0.31      0.30        62

      accuracy                           0.68      1340
     macro avg       0.24      0.29      0.25      1340
  weighted avg       0.80      0.68      0.73      1340

Confusion matrix (rows=true, columns=predicted):

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

,Asthma,Bronchiectasis,Bronchiolitis,COPD,Healthy,LRTI,Pneumonia,URTI
Asthma,0,0,0,0,0,0,0,0
Bronchiectasis,0,16,0,25,0,0,0,0
Bronchiolitis,0,0,0,0,9,0,1,9
COPD,0,63,31,824,22,5,120,8
Healthy,0,0,0,3,33,0,1,13
LRTI,0,0,0,0,0,0,0,0
Pneumonia,0,0,20,8,26,7,18,16
URTI,0,0,17,13,6,3,4,19

In [22]:

from sklearn.base import clone
from sklearn.metrics import confusion_matrix

# Fixed, patient-grouped splits
fold_splits = list(cv.split(X_dev, y_dev, groups=groups_dev))

oof_predictions = np.empty(len(y_dev), dtype=object)
oof_predictions[:] = None
fold_results = []
fold_feature_counts = []

for fold_number, (train_idx, val_idx) in enumerate(fold_splits, start=1):
    X_train = X_dev.iloc[train_idx]
    y_train = y_dev.iloc[train_idx]
    groups_train = groups_dev.iloc[train_idx]

    X_val = X_dev.iloc[val_idx]
    y_val = y_dev.iloc[val_idx]
    groups_val = groups_dev.iloc[val_idx]

    # Confirm patient-level separation
    overlap = set(groups_train) & set(groups_val)
    assert not overlap, f"Patient leakage in fold {fold_number}"

    # Select features using only the training portion
    fold_features, ranking = select_features_within_fold(
        X_train,
        y_train,
        correlation_threshold=0.90,
        random_state=42,
    )

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("svm", SVC(
            kernel="rbf",
            C=1.0,
            gamma="scale",
            class_weight="balanced",
            probability=False,
            random_state=42,
        )),
    ])

    model.fit(X_train[fold_features], y_train)
    predictions = model.predict(X_val[fold_features])

    # Store predictions at their original row positions
    oof_predictions[val_idx] = predictions
    fold_feature_counts.append(len(fold_features))

    fold_results.append({
        "fold": fold_number,
        "train_cycles": len(train_idx),
        "validation_cycles": len(val_idx),
        "train_patients": groups_train.nunique(),
        "validation_patients": groups_val.nunique(),
        "selected_features": len(fold_features),
        "accuracy": accuracy_score(y_val, predictions),
        "balanced_accuracy": balanced_accuracy_score(y_val, predictions),
        "macro_f1": f1_score(
            y_val, predictions, labels=ALL_CLASSES,
            average="macro", zero_division=0
        ),
        "weighted_f1": f1_score(
            y_val, predictions, average="weighted", zero_division=0
        ),
    })

    print(
        f"Fold {fold_number}/3 complete | "
        f"features={len(fold_features)} | "
        f"accuracy={accuracy_score(y_val, predictions):.4f} | "
        f"macro-F1={fold_results[-1]['macro_f1']:.4f}"
    )

assert all(pred is not None for pred in oof_predictions)

fold_results_df = pd.DataFrame(fold_results)

print("\nPER-FOLD RESULTS")
display(fold_results_df.round(4))

print("\nMEAN AND STANDARD DEVIATION ACROSS FOLDS")
display(
    fold_results_df[
        ["accuracy", "balanced_accuracy", "macro_f1", "weighted_f1"]
    ].agg(["mean", "std"]).round(4)
)

print("\nPOOLED OUT-OF-FOLD RESULTS")
print("Accuracy:", round(accuracy_score(y_dev, oof_predictions), 4))
print(
    "Balanced accuracy:",
    round(balanced_accuracy_score(y_dev, oof_predictions), 4),
)
print(
    "Macro-F1:",
    round(f1_score(
        y_dev, oof_predictions, labels=ALL_CLASSES,
        average="macro", zero_division=0
    ), 4),
)
print(
    "Weighted-F1:",
    round(f1_score(
        y_dev, oof_predictions, average="weighted", zero_division=0
    ), 4),
)

print("\nPOOLED CLASSIFICATION REPORT")
print(classification_report(
    y_dev,
    oof_predictions,
    labels=ALL_CLASSES,
    zero_division=0,
))

print("Selected feature counts by fold:", fold_feature_counts)

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Fold 1/3 complete | features=32 | accuracy=0.6791 | macro-F1=0.2519

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(
/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:2939: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Fold 2/3 complete | features=33 | accuracy=0.7585 | macro-F1=0.2614

/Users/vs/Sem 5/Respiratory-Disease-Classification/.venv/lib/python3.14/site-packages/sklearn/svm/_base.py:236: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Fold 3/3 complete | features=32 | accuracy=0.7020 | macro-F1=0.2077

PER-FOLD RESULTS

,fold,train_cycles,validation_cycles,train_patients,validation_patients,selected_features,accuracy,balanced_accuracy,macro_f1,weighted_f1
0,1,2685,1340,55,22,32,0.6791,0.3857,0.2519,0.7277
1,2,2679,1346,50,27,33,0.7585,0.3401,0.2614,0.7672
2,3,2686,1339,49,28,32,0.7020,0.2337,0.2077,0.7282

MEAN AND STANDARD DEVIATION ACROSS FOLDS

      accuracy  balanced_accuracy  macro_f1  weighted_f1
mean    0.7132             0.3198    0.2403       0.7410
std     0.0409             0.0780    0.0287       0.0227

POOLED OUT-OF-FOLD RESULTS
Accuracy: 0.7133
Balanced accuracy: 0.2787
Macro-F1: 0.2476
Weighted-F1: 0.7427

POOLED CLASSIFICATION REPORT
                precision    recall  f1-score   support

        Asthma       0.00      0.00      0.00         6
Bronchiectasis       0.22      0.28      0.25        90
 Bronchiolitis       0.00      0.00      0.00        74
          COPD       0.93      0.81      0.87      3220
       Healthy       0.30      0.57      0.40       147
          LRTI       0.00      0.00      0.00        32
     Pneumonia       0.23      0.38      0.28       285
          URTI       0.18      0.19      0.19       171

      accuracy                           0.71      4025
     macro avg       0.23      0.28      0.25      4025
  weighted avg       0.78      0.71      0.74      4025

Selected feature counts by fold: [32, 33, 32]